export type SupplementCategory =
  | 'mineral'
  | 'vitamin'
  | 'omega'
  | 'performance'
  | 'herbal'
  | 'electrolyte'
  | 'protein';

export interface Supplement {
  id: string;
  name: string;
  category: SupplementCategory;
  supports: string[];
  commonForms: string[];
  thingsToKnow: string;
  askProfessionalIf: string;
  tags: string[];
}

export const SUPPLEMENTS: Supplement[] = [
  {
    id: 'magnesium',
    name: 'Magnesium',
    category: 'mineral',
    supports: ['sleep quality', 'muscle relaxation', 'stress support', 'electrolyte balance'],
    commonForms: ['glycinate', 'citrate', 'malate', 'oxide'],
    thingsToKnow: 'Glycinate is often preferred for sleep and relaxation. Citrate may have a mild laxative effect. Avoid taking high doses with certain antibiotics.',
    askProfessionalIf: 'you have kidney disease, take blood pressure medications, or are on antibiotics.',
    tags: ['sleep', 'stress', 'recovery', 'digestion'],
  },
  {
    id: 'omega-3',
    name: 'Omega-3',
    category: 'omega',
    supports: ['heart health', 'inflammation support', 'cognitive function', 'joint comfort'],
    commonForms: ['fish oil', 'krill oil', 'algae oil (vegan)'],
    thingsToKnow: 'EPA and DHA are the active forms. Algae oil is a good plant-based alternative. High doses can thin blood slightly.',
    askProfessionalIf: 'you take blood thinners, have a bleeding disorder, or are scheduled for surgery.',
    tags: ['heart', 'cognition', 'joints', 'inflammation'],
  },
  {
    id: 'vitamin-d3',
    name: 'Vitamin D3',
    category: 'vitamin',
    supports: ['bone health', 'immune support', 'mood in darker months', 'calcium absorption'],
    commonForms: ['D3 (cholecalciferol)', 'D2 (ergocalciferol)'],
    thingsToKnow: 'D3 is generally more effective than D2 at raising blood levels. Fat-soluble, so it is best taken with a meal containing fat.',
    askProfessionalIf: 'you have kidney or liver disease, high calcium levels, or take medications that affect calcium.',
    tags: ['immunity', 'bone', 'mood'],
  },
  {
    id: 'creatine',
    name: 'Creatine',
    category: 'performance',
    supports: ['strength and power output', 'muscle performance', 'high-intensity exercise', 'cognitive support in some studies'],
    commonForms: ['creatine monohydrate', 'micronized creatine'],
    thingsToKnow: 'Monohydrate is the most researched and cost-effective form. May cause slight water retention in muscles. Not a steroid.',
    askProfessionalIf: 'you have pre-existing kidney conditions.',
    tags: ['performance', 'strength', 'recovery', 'cognition'],
  },
  {
    id: 'electrolytes',
    name: 'Electrolytes',
    category: 'electrolyte',
    supports: ['hydration', 'endurance support', 'muscle cramp reduction', 'fluid balance during sweat loss'],
    commonForms: ['sodium/potassium/magnesium blends', 'sports drink powders', 'tablet/capsule mixes'],
    thingsToKnow: 'Useful during long workouts, hot weather, or low-carb diets where electrolyte loss is higher. Avoid excessive sodium if you have hypertension.',
    askProfessionalIf: 'you have high blood pressure, kidney disease, or heart conditions.',
    tags: ['hydration', 'performance', 'recovery'],
  },
  {
    id: 'choline',
    name: 'Choline',
    category: 'vitamin',
    supports: ['cognition and memory', 'liver function support', 'cell membrane health', 'prenatal development'],
    commonForms: ['choline bitartrate', 'CDP-choline', 'Alpha-GPC'],
    thingsToKnow: 'Bitartrate is the budget-friendly form. Alpha-GPC and CDP-choline are commonly used for cognitive focus.',
    askProfessionalIf: 'you are pregnant, nursing, or have liver conditions.',
    tags: ['cognition', 'liver', 'prenatal'],
  },
  {
    id: 'zinc',
    name: 'Zinc',
    category: 'mineral',
    supports: ['immune function', 'wound healing', 'testosterone support in deficiency', 'skin health'],
    commonForms: ['zinc picolinate', 'zinc gluconate', 'zinc oxide'],
    thingsToKnow: 'Picolinate is generally well absorbed. Long-term high doses can deplete copper. Take away from iron and calcium for best absorption.',
    askProfessionalIf: 'you have a copper deficiency, take antibiotics, or are on immunosuppressants.',
    tags: ['immunity', 'skin', 'recovery'],
  },
  {
    id: 'vitamin-b12',
    name: 'Vitamin B12',
    category: 'vitamin',
    supports: ['energy metabolism', 'nerve health', 'red blood cell formation', 'cognitive clarity in deficiency'],
    commonForms: ['cyanocobalamin', 'methylcobalamin', 'sublingual drops'],
    thingsToKnow: 'Methylcobalamin is the active form. Deficiency is more common in vegans, vegetarians, and older adults.',
    askProfessionalIf: 'you have pernicious anemia, digestive disorders, or take metformin long-term.',
    tags: ['energy', 'cognition', 'blood'],
  },
  {
    id: 'iron',
    name: 'Iron',
    category: 'mineral',
    supports: ['oxygen transport', 'energy in deficiency', 'red blood cell production'],
    commonForms: ['ferrous bisglycinate', 'ferrous sulfate', 'heme iron polypeptide'],
    thingsToKnow: 'Bisglycinate is often gentler on the stomach than sulfate. Vitamin C improves absorption; calcium, coffee, and tea reduce it.',
    askProfessionalIf: 'you are male with normal iron levels, have hemochromatosis, or are not confirmed deficient.',
    tags: ['energy', 'blood', 'women'],
  },
  {
    id: 'ashwagandha',
    name: 'Ashwagandha',
    category: 'herbal',
    supports: ['stress resilience', 'sleep quality', 'recovery from exercise', 'mood balance'],
    commonForms: ['KSM-66', 'Sensoril', 'root powder'],
    thingsToKnow: 'KSM-66 is a full-spectrum root extract. Sensoril is a more concentrated blend. Effects may take 2–4 weeks to notice.',
    askProfessionalIf: 'you have thyroid conditions, autoimmune disease, or take sedatives.',
    tags: ['stress', 'sleep', 'recovery', 'mood'],
  },
  {
    id: 'caffeine',
    name: 'Caffeine',
    category: 'performance',
    supports: ['alertness and focus', 'exercise performance', 'fatigue reduction', 'metabolism support temporarily'],
    commonForms: ['coffee', 'tea', 'anhydrous caffeine pills', 'pre-workout powders'],
    thingsToKnow: 'Effects vary by genetics and tolerance. Avoid late-day use to protect sleep. Can raise heart rate and blood pressure temporarily.',
    askProfessionalIf: 'you have heart conditions, anxiety disorders, high blood pressure, or are pregnant.',
    tags: ['energy', 'performance', 'cognition'],
  },
  {
    id: 'whey-protein',
    name: 'Whey Protein',
    category: 'protein',
    supports: ['muscle protein synthesis', 'convenient protein intake', 'post-workout recovery', 'satiety'],
    commonForms: ['whey isolate', 'whey concentrate', 'hydrolyzed whey'],
    thingsToKnow: 'Isolate has more protein and less lactose than concentrate. Hydrolyzed may digest faster but is more expensive.',
    askProfessionalIf: 'you have dairy allergies or severe lactose intolerance.',
    tags: ['performance', 'recovery', 'muscle', 'weight-management'],
  },
  {
    id: 'casein',
    name: 'Casein',
    category: 'protein',
    supports: ['slow-release protein overnight', 'muscle recovery during sleep', 'prolonged satiety'],
    commonForms: ['micellar casein', 'casein hydrolysate'],
    thingsToKnow: 'Micellar casein digests slowly, making it popular before bed. Thicker texture than whey.',
    askProfessionalIf: 'you have dairy allergies or severe lactose intolerance.',
    tags: ['recovery', 'sleep', 'muscle'],
  },
  {
    id: 'collagen',
    name: 'Collagen',
    category: 'protein',
    supports: ['skin elasticity', 'joint comfort', 'hair and nail strength', 'tissue repair support'],
    commonForms: ['hydrolyzed collagen peptides', 'marine collagen', 'bovine collagen'],
    thingsToKnow: 'Not a complete protein source. Peptides are broken down for easier absorption. Results typically take 8–12 weeks.',
    askProfessionalIf: 'you have allergies to fish or beef sources.',
    tags: ['joints', 'skin', 'recovery'],
  },
  {
    id: 'turmeric',
    name: 'Turmeric / Curcumin',
    category: 'herbal',
    supports: ['inflammation support', 'joint comfort', 'antioxidant activity', 'digestive wellness'],
    commonForms: ['curcumin extract', 'turmeric root powder', 'Meriva', 'Longvida'],
    thingsToKnow: 'Curcumin is poorly absorbed alone. Look for formulations with piperine (black pepper extract) or liposomal delivery.',
    askProfessionalIf: 'you take blood thinners, have gallbladder issues, or are scheduled for surgery.',
    tags: ['inflammation', 'joints', 'digestion', 'antioxidant'],
  },
  {
    id: 'probiotics',
    name: 'Probiotics',
    category: 'herbal',
    supports: ['digestive health', 'gut microbiome balance', 'immune support', 'bloating relief in some users'],
    commonForms: ['Lactobacillus blends', 'Bifidobacterium blends', 'spore-based probiotics'],
    thingsToKnow: 'Strain matters more than CFU count alone. Some people experience temporary gas when starting. Store refrigerated unless labeled shelf-stable.',
    askProfessionalIf: 'you are immunocompromised, have a central line, or have severe illness.',
    tags: ['digestion', 'immunity', 'gut-health'],
  },
  {
    id: 'fiber',
    name: 'Fiber',
    category: 'herbal',
    supports: ['digestive regularity', 'satiety and appetite', 'blood sugar stability', 'gut health'],
    commonForms: ['psyllium husk', 'inulin', 'methylcellulose', 'acacia fiber'],
    thingsToKnow: 'Psyllium is well studied for cholesterol and regularity. Increase intake gradually and drink plenty of water to avoid bloating.',
    askProfessionalIf: 'you have a history of bowel obstruction, Crohn’s disease, or swallowing difficulties.',
    tags: ['digestion', 'weight-management', 'heart'],
  },
  {
    id: 'melatonin',
    name: 'Melatonin',
    category: 'herbal',
    supports: ['sleep onset', 'circadian rhythm adjustment', 'jet lag relief', 'sleep quality in shift workers'],
    commonForms: ['immediate-release tablets', 'extended-release tablets', 'liquid drops', 'gummies'],
    thingsToKnow: 'Lower doses (0.3–1mg) are often as effective as higher doses. Best used short-term or for jet lag.',
    askProfessionalIf: 'you are pregnant, nursing, have autoimmune conditions, or take blood thinners or sedatives.',
    tags: ['sleep', 'stress', 'jet-lag'],
  },
  {
    id: 'coq10',
    name: 'CoQ10',
    category: 'vitamin',
    supports: ['cellular energy production', 'heart health', 'antioxidant support', 'statin-associated fatigue'],
    commonForms: ['ubiquinone', 'ubiquinol'],
    thingsToKnow: 'Ubiquinol is the reduced form and may absorb better, especially in older adults. Levels naturally decline with age.',
    askProfessionalIf: 'you take blood thinners, blood pressure medications, or chemotherapy.',
    tags: ['heart', 'energy', 'antioxidant'],
  },
  {
    id: 'beta-alanine',
    name: 'Beta-Alanine',
    category: 'performance',
    supports: ['muscular endurance', 'high-intensity exercise capacity', 'buffering of muscle acidity'],
    commonForms: ['beta-alanine powder', 'capsules', 'pre-workout blends'],
    thingsToKnow: 'Can cause a harmless tingling sensation (paresthesia). Most effective when taken consistently over several weeks.',
    askProfessionalIf: 'you have kidney or liver disease.',
    tags: ['performance', 'endurance', 'strength'],
  },
];

export const SUPPLEMENT_TAGS = [
  'sleep',
  'stress',
  'energy',
  'recovery',
  'digestion',
  'immunity',
  'cognition',
  'joints',
  'performance',
  'hydration',
  'heart',
  'skin',
  'muscle',
  'weight-management',
  'inflammation',
  'antioxidant',
  'blood',
  'bone',
  'mood',
  'gut-health',
] as const;

export type SupplementTag = (typeof SUPPLEMENT_TAGS)[number];
