import {
  DayType,
  EquipmentCategory,
  ExerciseTier,
  ExperienceLevel,
  FatigueCost,
  GoalBucket,
  LiftComfort,
  MovementPattern,
  ProgressionModel,
  ReplacementGroup,
  SessionEnvironment,
  SetupComplexity,
  SlotArchetype,
  TrainingStyle,
} from '../../types/v1_engine';

// --- SEED V1 EXERCISES (Sample of the ~80 anchors) ---
export const v1_exercises = [
  {
    external_id: 'ex_bb_back_squat',
    name: 'Barbell Back Squat',
    movement_pattern: MovementPattern.Squat,
    architectural_group: ReplacementGroup.Primary_Bilateral_Squat,
    equipment_category: EquipmentCategory.Barbell,
    is_unilateral: false,
    setup_complexity: SetupComplexity.High,
    fatigue_cost: FatigueCost.High,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Linear_Load, ProgressionModel.Double_Progression, ProgressionModel.Top_Set_Backoff],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_leg_press',
    name: 'Leg Press',
    movement_pattern: MovementPattern.Squat,
    architectural_group: ReplacementGroup.Primary_Bilateral_Squat,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression, ProgressionModel.Linear_Load],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_goblet_squat',
    name: 'Goblet Squat',
    movement_pattern: MovementPattern.Squat,
    architectural_group: ReplacementGroup.Primary_Bilateral_Squat,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_bb_deadlift',
    name: 'Barbell Deadlift',
    movement_pattern: MovementPattern.Hinge,
    architectural_group: ReplacementGroup.Primary_Bilateral_Hinge,
    equipment_category: EquipmentCategory.Barbell,
    is_unilateral: false,
    setup_complexity: SetupComplexity.High,
    fatigue_cost: FatigueCost.High,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Linear_Load, ProgressionModel.Top_Set_Backoff],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_bb_flat_bench',
    name: 'Barbell Bench Press',
    movement_pattern: MovementPattern.HPress,
    architectural_group: ReplacementGroup.Primary_Horizontal_Press,
    equipment_category: EquipmentCategory.Barbell,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Linear_Load, ProgressionModel.Double_Progression],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_db_flat_bench',
    name: 'DB Flat Bench Press',
    movement_pattern: MovementPattern.HPress,
    architectural_group: ReplacementGroup.Primary_Horizontal_Press,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_lat_pulldown',
    name: 'Lat Pulldown',
    movement_pattern: MovementPattern.VPull,
    architectural_group: ReplacementGroup.Primary_Vertical_Pull,
    equipment_category: EquipmentCategory.Cable,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_pull_up',
    name: 'Pull-Up',
    movement_pattern: MovementPattern.VPull,
    architectural_group: ReplacementGroup.Primary_Vertical_Pull,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Mechanical_BW, ProgressionModel.Rep_Goal],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_cable_curl',
    name: 'Cable Bicep Curl',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Bicep_Flexion,
    equipment_category: EquipmentCategory.Cable,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_crunch',
    name: 'Basic Crunch',
    movement_pattern: MovementPattern.Core,
    architectural_group: ReplacementGroup.Trunk_Flexion,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Rep_Goal],
    estimated_duration_seconds: 30,
  },
];

// --- SEED PLAN FAMILIES ---
export const v1_plan_families = [
  {
    external_id: 'fam_beginner_fullbody_v1',
    name: 'Beginner Full Body v1',
    goal_bucket: GoalBucket.GenFitness,
    training_style: TrainingStyle.FullBody,
    days_per_week: 3,
    lift_comfort: LiftComfort.BarbellAdv,
    environment: SessionEnvironment.Commercial,
    progression_model: ProgressionModel.Linear_Load,
  },
  {
    external_id: 'fam_longevity_upper_lower_v1',
    name: 'General Fitness Upper/Lower (Longevity Bias) v1',
    goal_bucket: GoalBucket.GenFitness,
    training_style: TrainingStyle.UpperLower,
    days_per_week: 4,
    lift_comfort: LiftComfort.MachineDB,
    environment: SessionEnvironment.Commercial,
    progression_model: ProgressionModel.Double_Progression,
  },
  {
    external_id: 'fam_hypertrophy_ppl_v1',
    name: 'Hypertrophy PPL v1',
    goal_bucket: GoalBucket.Hypertrophy,
    training_style: TrainingStyle.PPL,
    days_per_week: 6,
    lift_comfort: LiftComfort.BarbellAdv,
    environment: SessionEnvironment.Commercial,
    progression_model: ProgressionModel.Double_Progression,
  }
];

// --- SEED TEMPLATES (Only block 1 included as sample) ---
export const v1_templates = [
  {
    family_ref: 'fam_beginner_fullbody_v1', // Linked by script later
    external_id: 'tpl_beginner_fullbody_v1_blk1',
    name: 'Beginner Full Body Phase 1',
    block_number: 1,
    difficulty_score: 2,
    days: [
      {
        day_number: 1,
        day_type: DayType.FullBodyStrength,
        slots: [
          {
            order_index: 0,
            architectural_group: ReplacementGroup.Primary_Bilateral_Squat,
            is_required: true,
            archetype: SlotArchetype.PrimeCompound,
            progression_model: ProgressionModel.Linear_Load,
            sets: 3,
            reps_min: 8,
            reps_max: 10,
            target_rpe: 7,
            rest_seconds: 120,
          },
          {
            order_index: 1,
            architectural_group: ReplacementGroup.Primary_Horizontal_Press,
            is_required: true,
            archetype: SlotArchetype.SecondaryCompound,
            progression_model: ProgressionModel.Linear_Load,
            sets: 3,
            reps_min: 8,
            reps_max: 10,
            target_rpe: 7,
            rest_seconds: 120,
          },
          {
            order_index: 2,
            architectural_group: ReplacementGroup.Primary_Horizontal_Pull,
            is_required: true,
            archetype: SlotArchetype.SecondaryCompound,
            progression_model: ProgressionModel.Linear_Load,
            sets: 3,
            reps_min: 10,
            reps_max: 12,
            target_rpe: 8,
            rest_seconds: 90,
          },
          {
            order_index: 3,
            architectural_group: ReplacementGroup.Trunk_Flexion,
            is_required: true,
            archetype: SlotArchetype.Finisher,
            progression_model: ProgressionModel.Rep_Goal,
            sets: 3,
            reps_min: 12,
            reps_max: 15,
            target_rpe: 8,
            rest_seconds: 60,
          }
        ]
      }
      // Future days would go here
    ]
  }
];
