import {
  MovementPattern,
  ReplacementGroup,
  EquipmentCategory,
  SetupComplexity,
  FatigueCost,
  ExerciseTier,
  ProgressionModel,
  ContraindicationTag,
} from '../../types/v1_engine.ts';

export const coreExercises = [
  {
    external_id: 'ex_barbell_back_squat',
    name: 'Barbell Back Squat',
    movement_pattern: MovementPattern.Squat,
    architectural_group: ReplacementGroup.Primary_Bilateral_Squat,
    equipment_category: EquipmentCategory.Barbell,
    is_unilateral: false,
    setup_complexity: SetupComplexity.High,
    fatigue_cost: FatigueCost.High,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Linear_Load, ProgressionModel.Double_Progression, ProgressionModel.Top_Set_Backoff],
    contraindications: [],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_leg_press',
    name: 'Leg Press',
    movement_pattern: MovementPattern.Squat,
    architectural_group: ReplacementGroup.Primary_Bilateral_Squat,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression, ProgressionModel.Linear_Load],
    contraindications: [],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_goblet_squat',
    name: 'Goblet Squat',
    movement_pattern: MovementPattern.Squat,
    architectural_group: ReplacementGroup.Primary_Bilateral_Squat,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_bw_squat',
    name: 'Bodyweight Squat',
    movement_pattern: MovementPattern.Squat,
    architectural_group: ReplacementGroup.Primary_Bilateral_Squat,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Mechanical_BW, ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_hack_squat',
    name: 'Hack Squat',
    movement_pattern: MovementPattern.Squat,
    architectural_group: ReplacementGroup.Primary_Bilateral_Squat,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_barbell_front_squat',
    name: 'Barbell Front Squat',
    movement_pattern: MovementPattern.Squat,
    architectural_group: ReplacementGroup.Primary_Bilateral_Squat,
    equipment_category: EquipmentCategory.Barbell,
    is_unilateral: false,
    setup_complexity: SetupComplexity.High,
    fatigue_cost: FatigueCost.High,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Linear_Load],
    contraindications: [ContraindicationTag.Wrist_Extension],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    movement_pattern: MovementPattern.Squat,
    architectural_group: ReplacementGroup.Unilateral_Squat_Lunge,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: true,
    setup_complexity: SetupComplexity.High,
    fatigue_cost: FatigueCost.High,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_walking_lunge',
    name: 'Walking Lunge',
    movement_pattern: MovementPattern.Squat,
    architectural_group: ReplacementGroup.Unilateral_Squat_Lunge,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: true,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.High,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression, ProgressionModel.Tempo],
    contraindications: [],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_bw_lunge',
    name: 'Bodyweight Lunge',
    movement_pattern: MovementPattern.Squat,
    architectural_group: ReplacementGroup.Unilateral_Squat_Lunge,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: true,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Mechanical_BW, ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_barbell_deadlift',
    name: 'Barbell Deadlift',
    movement_pattern: MovementPattern.Hinge,
    architectural_group: ReplacementGroup.Primary_Bilateral_Hinge,
    equipment_category: EquipmentCategory.Barbell,
    is_unilateral: false,
    setup_complexity: SetupComplexity.High,
    fatigue_cost: FatigueCost.High,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Linear_Load, ProgressionModel.Top_Set_Backoff],
    contraindications: [ContraindicationTag.Lower_Back_Shearing],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_barbell_rdl',
    name: 'Romanian Deadlift',
    movement_pattern: MovementPattern.Hinge,
    architectural_group: ReplacementGroup.Primary_Bilateral_Hinge,
    equipment_category: EquipmentCategory.Barbell,
    is_unilateral: false,
    setup_complexity: SetupComplexity.High,
    fatigue_cost: FatigueCost.High,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Linear_Load, ProgressionModel.Double_Progression],
    contraindications: [ContraindicationTag.Lower_Back_Shearing],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_db_rdl',
    name: 'DB RDL',
    movement_pattern: MovementPattern.Hinge,
    architectural_group: ReplacementGroup.Primary_Bilateral_Hinge,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [ContraindicationTag.Lower_Back_Shearing],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_bw_glute_bridge',
    name: 'Glute Bridge',
    movement_pattern: MovementPattern.Hinge,
    architectural_group: ReplacementGroup.Primary_Bilateral_Hinge,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Mechanical_BW],
    contraindications: [],
    estimated_duration_seconds: 30,
  },
  // UNILATERAL HINGE EXERCISES - Required for Unilateral_Hinge slot hydration
  // These exercises are tagged with is_unilateral=true to match UnilateralGroupMapping logic
  {
    external_id: 'ex_single_arm_db_rdl',
    name: 'Single Arm DB RDL',
    movement_pattern: MovementPattern.Hinge,
    architectural_group: ReplacementGroup.Primary_Bilateral_Hinge, // Base group for mapping
    equipment_category: EquipmentCategory.DB,
    is_unilateral: true, // Marked as unilateral for Unilateral_Hinge matching
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [ContraindicationTag.Lower_Back_Shearing],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_single_leg_rdl',
    name: 'Single Leg RDL',
    movement_pattern: MovementPattern.Hinge,
    architectural_group: ReplacementGroup.Primary_Bilateral_Hinge,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: true,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Mechanical_BW],
    contraindications: [],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_single_leg_glute_bridge',
    name: 'Single Leg Glute Bridge',
    movement_pattern: MovementPattern.Hinge,
    architectural_group: ReplacementGroup.Primary_Bilateral_Hinge,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: true,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Mechanical_BW],
    contraindications: [],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_barbell_bench_press',
    name: 'Barbell Bench Press',
    movement_pattern: MovementPattern.HPress,
    architectural_group: ReplacementGroup.Primary_Horizontal_Press,
    equipment_category: EquipmentCategory.Barbell,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Linear_Load, ProgressionModel.Top_Set_Backoff, ProgressionModel.Double_Progression],
    contraindications: [ContraindicationTag.Shoulder_Impingement],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_db_flat_bench_press',
    name: 'Flat Dumbbell Bench Press',
    movement_pattern: MovementPattern.HPress,
    architectural_group: ReplacementGroup.Primary_Horizontal_Press,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_push_up',
    name: 'Push-Up',
    movement_pattern: MovementPattern.HPress,
    architectural_group: ReplacementGroup.Primary_Horizontal_Press,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Mechanical_BW, ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_machine_chest_press',
    name: 'Machine Chest Press',
    movement_pattern: MovementPattern.HPress,
    architectural_group: ReplacementGroup.Primary_Horizontal_Press,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_barbell_ohp',
    name: 'Barbell OHP',
    movement_pattern: MovementPattern.VPress,
    architectural_group: ReplacementGroup.Primary_Vertical_Press,
    equipment_category: EquipmentCategory.Barbell,
    is_unilateral: false,
    setup_complexity: SetupComplexity.High,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Linear_Load, ProgressionModel.Double_Progression],
    contraindications: [ContraindicationTag.Shoulder_Impingement],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_seated_db_press',
    name: 'Seated Dumbbell Overhead Press',
    movement_pattern: MovementPattern.VPress,
    architectural_group: ReplacementGroup.Primary_Vertical_Press,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_pike_push_up',
    name: 'Pike Push-Up',
    movement_pattern: MovementPattern.VPress,
    architectural_group: ReplacementGroup.Primary_Vertical_Press,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Mechanical_BW],
    contraindications: [],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_pull_up',
    name: 'Pull-Up',
    movement_pattern: MovementPattern.VPull,
    architectural_group: ReplacementGroup.Primary_Vertical_Pull,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Mechanical_BW, ProgressionModel.Rep_Goal],
    contraindications: [],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_lat_pulldown',
    name: 'Lat Pulldown (Wide-Grip)',
    movement_pattern: MovementPattern.VPull,
    architectural_group: ReplacementGroup.Primary_Vertical_Pull,
    equipment_category: EquipmentCategory.Cable,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_db_1_arm_row',
    name: 'Dumbbell Row',
    movement_pattern: MovementPattern.HPull,
    architectural_group: ReplacementGroup.Primary_Horizontal_Pull,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: true,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_inverted_row',
    name: 'Inverted Row',
    movement_pattern: MovementPattern.HPull,
    architectural_group: ReplacementGroup.Primary_Horizontal_Pull,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Mechanical_BW],
    contraindications: [],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_barbell_row',
    name: 'Barbell Row',
    movement_pattern: MovementPattern.HPull,
    architectural_group: ReplacementGroup.Primary_Horizontal_Pull,
    equipment_category: EquipmentCategory.Barbell,
    is_unilateral: false,
    setup_complexity: SetupComplexity.High,
    fatigue_cost: FatigueCost.High,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression, ProgressionModel.Linear_Load],
    contraindications: [ContraindicationTag.Lower_Back_Shearing],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_cable_seated_row',
    name: 'Cable Seated Row',
    movement_pattern: MovementPattern.HPull,
    architectural_group: ReplacementGroup.Primary_Horizontal_Pull,
    equipment_category: EquipmentCategory.Cable,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_db_lateral_raise',
    name: 'DB Lateral Raise',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Lateral_Delt,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_cable_lateral_raise',
    name: 'Cable Lateral Raise',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Lateral_Delt,
    equipment_category: EquipmentCategory.Cable,
    is_unilateral: true,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_db_bicep_curl',
    name: 'Alternating Dumbbell Curl',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Bicep_Flexion,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_tricep_rope_pushdown',
    name: 'Tricep Rope Pushdown',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Tricep_Extension,
    equipment_category: EquipmentCategory.Cable,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_seated_leg_curl',
    name: 'Seated Leg Curl',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Hamstring_Curl,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_chest_fly_machine',
    name: 'Pec Deck Flye',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Chest_Fly,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_quad_extension',
    name: 'Leg Extension',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Quad_Extension,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_calf_raise_standing',
    name: 'Standing Calf Raise',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Calf_Raise,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_calf_raise_bodyweight',
    name: 'Bodyweight Calf Raise',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Calf_Raise,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T3,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_calf_raise_single_leg_bw',
    name: 'Single Leg Calf Raise',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Calf_Raise,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: true,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T3,
    progression_types: [ProgressionModel.Double_Progression],
    contraindications: [],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_trunk_flexion_crunch',
    name: 'Crunch',
    movement_pattern: MovementPattern.Core,
    architectural_group: ReplacementGroup.Trunk_Flexion,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Rep_Goal],
    contraindications: [],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_trunk_anti_ext_plank',
    name: 'Plank',
    movement_pattern: MovementPattern.Core,
    architectural_group: ReplacementGroup.Trunk_Anti_Extension,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Rep_Goal],
    contraindications: [],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_metabolic_finisher',
    name: 'Burpees',
    movement_pattern: MovementPattern.Cond,
    architectural_group: ReplacementGroup.Conditioning_Metabolic_Finisher,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.High,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Rep_Goal],
    contraindications: [],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_machine_shoulder_press',
    name: 'Machine Shoulder Press',
    movement_pattern: MovementPattern.VPress,
    architectural_group: ReplacementGroup.Primary_Vertical_Press,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_machine_row_seated',
    name: 'Machine Seated Row',
    movement_pattern: MovementPattern.HPull,
    architectural_group: ReplacementGroup.Primary_Horizontal_Pull,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_smith_machine_squat',
    name: 'Smith Machine Squat',
    movement_pattern: MovementPattern.Squat,
    architectural_group: ReplacementGroup.Primary_Bilateral_Squat,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Linear_Load, ProgressionModel.Double_Progression],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_smith_machine_bench_press',
    name: 'Smith Machine Bench Press',
    movement_pattern: MovementPattern.HPress,
    architectural_group: ReplacementGroup.Primary_Horizontal_Press,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Linear_Load, ProgressionModel.Double_Progression],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_db_incline_bench_press',
    name: 'DB Incline Bench Press',
    movement_pattern: MovementPattern.HPress,
    architectural_group: ReplacementGroup.Primary_Horizontal_Press,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_db_shoulder_press_seated',
    name: 'Seated DB Shoulder Press',
    movement_pattern: MovementPattern.VPress,
    architectural_group: ReplacementGroup.Primary_Vertical_Press,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_db_split_squat',
    name: 'Bulgarian Split Squat',
    movement_pattern: MovementPattern.Squat,
    architectural_group: ReplacementGroup.Unilateral_Squat_Lunge,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: true,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_cable_face_pull',
    name: 'Cable Face Pull',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Primary_Horizontal_Pull,
    equipment_category: EquipmentCategory.Cable,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_cable_bicep_curl',
    name: 'Cable Bicep Curl',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Bicep_Flexion,
    equipment_category: EquipmentCategory.Cable,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_cable_overhead_tricep_ext',
    name: 'Cable Overhead Tricep Extension',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Tricep_Extension,
    equipment_category: EquipmentCategory.Cable,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_bw_chin_up',
    name: 'Chin-Up',
    movement_pattern: MovementPattern.VPull,
    architectural_group: ReplacementGroup.Primary_Vertical_Pull,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Mechanical_BW, ProgressionModel.Rep_Goal],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_bw_dip',
    name: 'Bodyweight Dip',
    movement_pattern: MovementPattern.HPress,
    architectural_group: ReplacementGroup.Primary_Horizontal_Press,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Mechanical_BW, ProgressionModel.Rep_Goal],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_bw_deadbug',
    name: 'Deadbug',
    movement_pattern: MovementPattern.Core,
    architectural_group: ReplacementGroup.Trunk_Anti_Extension,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Rep_Goal],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_bw_glute_bridge',
    name: 'Glute Bridge',
    movement_pattern: MovementPattern.Hinge,
    architectural_group: ReplacementGroup.Primary_Bilateral_Hinge,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Rep_Goal],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_lying_leg_curl',
    name: 'Lying Leg Curl',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Hamstring_Curl,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_pec_deck',
    name: 'Pec Deck',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Chest_Fly,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_smith_machine_rdl',
    name: 'Smith Machine RDL',
    movement_pattern: MovementPattern.Hinge,
    architectural_group: ReplacementGroup.Primary_Bilateral_Hinge,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_db_hammer_curl',
    name: 'DB Hammer Curl',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Bicep_Flexion,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_db_skull_crusher',
    name: 'DB Skull Crusher',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Tricep_Extension,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_cable_pull_through',
    name: 'Cable Pull Through',
    movement_pattern: MovementPattern.Hinge,
    architectural_group: ReplacementGroup.Primary_Bilateral_Hinge,
    equipment_category: EquipmentCategory.Cable,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_bw_bird_dog',
    name: 'Bird-Dog',
    movement_pattern: MovementPattern.Core,
    architectural_group: ReplacementGroup.Trunk_Anti_Extension,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Rep_Goal],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_bw_side_plank',
    name: 'Side Plank',
    movement_pattern: MovementPattern.Core,
    architectural_group: ReplacementGroup.Trunk_Anti_Extension,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: true,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Rep_Goal],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_machine_lat_pulldown',
    name: 'Machine Lat Pulldown',
    movement_pattern: MovementPattern.VPull,
    architectural_group: ReplacementGroup.Primary_Vertical_Pull,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_assisted_pull_up_machine',
    name: 'Assisted Pull-Up Machine',
    movement_pattern: MovementPattern.VPull,
    architectural_group: ReplacementGroup.Primary_Vertical_Pull,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_db_goblet_lunge',
    name: 'DB Goblet Lunge',
    movement_pattern: MovementPattern.Squat,
    architectural_group: ReplacementGroup.Unilateral_Squat_Lunge,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: true,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_cable_straight_arm_pulldown',
    name: 'Cable Straight Arm Pulldown',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Primary_Vertical_Pull,
    equipment_category: EquipmentCategory.Cable,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_bw_inverted_row',
    name: 'Inverted Row',
    movement_pattern: MovementPattern.HPull,
    architectural_group: ReplacementGroup.Primary_Horizontal_Pull,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Mechanical_BW, ProgressionModel.Rep_Goal],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_bw_mountain_climbers',
    name: 'Mountain Climbers',
    movement_pattern: MovementPattern.Cond,
    architectural_group: ReplacementGroup.Conditioning_Metabolic_Finisher,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Rep_Goal],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_db_step_up',
    name: 'DB Step-Up',
    movement_pattern: MovementPattern.Squat,
    architectural_group: ReplacementGroup.Unilateral_Squat_Lunge,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: true,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_cable_crunch',
    name: 'Cable Crunch',
    movement_pattern: MovementPattern.Core,
    architectural_group: ReplacementGroup.Trunk_Flexion,
    equipment_category: EquipmentCategory.Cable,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_machine_tricep_extension',
    name: 'Machine Tricep Extension',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Tricep_Extension,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_machine_preacher_curl',
    name: 'Machine Preacher Curl',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Isolation_Bicep_Flexion,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_db_rearguard_delt_fly',
    name: 'DB Rear Delt Fly',
    movement_pattern: MovementPattern.Iso,
    architectural_group: ReplacementGroup.Primary_Horizontal_Pull,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_bw_hollow_hold',
    name: 'Hollow Hold',
    movement_pattern: MovementPattern.Core,
    architectural_group: ReplacementGroup.Trunk_Anti_Extension,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Rep_Goal],
    estimated_duration_seconds: 60,
  },
  {
    external_id: 'ex_bw_single_leg_bridge',
    name: 'Single Leg Glute Bridge',
    movement_pattern: MovementPattern.Hinge,
    architectural_group: ReplacementGroup.Primary_Bilateral_Hinge,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: true,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Rep_Goal],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_cable_woodchop',
    name: 'Cable Woodchop',
    movement_pattern: MovementPattern.Core,
    architectural_group: ReplacementGroup.Trunk_Anti_Extension,
    equipment_category: EquipmentCategory.Cable,
    is_unilateral: true,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_machine_chest_press_incline',
    name: 'Incline Machine Chest Press',
    movement_pattern: MovementPattern.HPress,
    architectural_group: ReplacementGroup.Primary_Horizontal_Press,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_db_chest_supported_row',
    name: 'DB Chest Supported Row',
    movement_pattern: MovementPattern.HPull,
    architectural_group: ReplacementGroup.Primary_Horizontal_Pull,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_cable_seated_high_row',
    name: 'Cable Seated High Row',
    movement_pattern: MovementPattern.HPull,
    architectural_group: ReplacementGroup.Primary_Horizontal_Pull,
    equipment_category: EquipmentCategory.Cable,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_smith_machine_incl_press',
    name: 'Smith Machine Incline Press',
    movement_pattern: MovementPattern.HPress,
    architectural_group: ReplacementGroup.Primary_Horizontal_Press,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_smith_machine_ohp',
    name: 'Smith Machine Over Head Press',
    movement_pattern: MovementPattern.VPress,
    architectural_group: ReplacementGroup.Primary_Vertical_Press,
    equipment_category: EquipmentCategory.Machine,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Medium,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_db_romanian_deadlift_1_arm',
    name: 'Single Arm DB RDL',
    movement_pattern: MovementPattern.Hinge,
    architectural_group: ReplacementGroup.Primary_Bilateral_Hinge,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: true,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_cable_chest_press_standing',
    name: 'Standing Cable Chest Press',
    movement_pattern: MovementPattern.HPress,
    architectural_group: ReplacementGroup.Primary_Horizontal_Press,
    equipment_category: EquipmentCategory.Cable,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Double_Progression],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_bw_box_jump',
    name: 'Box Jump',
    movement_pattern: MovementPattern.Cond,
    architectural_group: ReplacementGroup.Power_Dynamic_Primer,
    equipment_category: EquipmentCategory.BW,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Medium,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Rep_Goal],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_med_ball_slam',
    name: 'Medicine Ball Slam',
    movement_pattern: MovementPattern.Cond,
    architectural_group: ReplacementGroup.Power_Dynamic_Primer,
    equipment_category: EquipmentCategory.Misc,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Rep_Goal],
    estimated_duration_seconds: 30,
  },
  {
    external_id: 'ex_cable_pallof_press',
    name: 'Pallof Press',
    movement_pattern: MovementPattern.Core,
    architectural_group: ReplacementGroup.Trunk_Rotational_Anti_Rotation,
    equipment_category: EquipmentCategory.Cable,
    is_unilateral: true,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T1,
    progression_types: [ProgressionModel.Tempo, ProgressionModel.Rep_Goal],
    estimated_duration_seconds: 45,
  },
  {
    external_id: 'ex_db_russian_twist',
    name: 'DB Russian Twist',
    movement_pattern: MovementPattern.Core,
    architectural_group: ReplacementGroup.Trunk_Rotational_Anti_Rotation,
    equipment_category: EquipmentCategory.DB,
    is_unilateral: false,
    setup_complexity: SetupComplexity.Low,
    fatigue_cost: FatigueCost.Low,
    tier: ExerciseTier.T2,
    progression_types: [ProgressionModel.Rep_Goal],
    estimated_duration_seconds: 45,
  }
];
