import { GoalBucket, ExperienceLevel, SessionEnvironment, LiftComfort } from '../../types/v1_engine.ts';

export const planFamilies = [
  {
    external_id: 'fam_beginner_fb',
    name: 'Beginner Full Body (Standard)',
    description: 'A well-rounded full body program for novices with commercial gym access.',
    template_id: 'tmp_beginner_fb_v1',
    experience_level: ExperienceLevel.Beginner,
    goal_bucket: GoalBucket.GenFitness,
  },
  {
    external_id: 'fam_beginner_machine_fb',
    name: 'Beginner Machine-Focus Full Body',
    description: 'Novice-friendly full body work using machines and dumbbells for maximum safety.',
    template_id: 'tmp_beginner_machine_fb_v1',
    experience_level: ExperienceLevel.Beginner,
    goal_bucket: GoalBucket.GenFitness,
  },
  {
    external_id: 'fam_hyp_fb',
    name: 'Hypertrophy Full Body (3-Day)',
    description: 'Maximum efficiency for muscle growth via high-frequency full body stimulation.',
    template_id: 'tmp_hyp_fb_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Hypertrophy,
  },
  {
    external_id: 'fam_hyp_ul',
    name: 'Hypertrophy Upper/Lower (4-Day)',
    description: 'The industry-standard split for building lean muscle mass.',
    template_id: 'tmp_hyp_ul_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Hypertrophy,
  },
  {
    external_id: 'fam_hyp_ppl',
    name: 'Hypertrophy PPL (5-6 Day)',
    description: 'High volume bodybuilding split for advanced trainees.',
    template_id: 'tmp_hyp_ppl_v1',
    experience_level: ExperienceLevel.Advanced,
    goal_bucket: GoalBucket.Hypertrophy,
  },
  {
    external_id: 'fam_fatloss_fb',
    name: 'Metabolic Fat Loss Full Body',
    description: 'Preserve muscle while maximizing caloric burn through high-density work.',
    template_id: 'tmp_fatloss_fb_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.FatLoss,
  },
  {
    external_id: 'fam_str_fb',
    name: 'Strength Full Body (3-Day)',
    description: 'Barbell-focused strength development for those on a tight schedule.',
    template_id: 'tmp_str_fb_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Strength,
  },
  {
    external_id: 'fam_str_ul',
    name: 'Strength Upper/Lower (4-Day)',
    description: 'Heavy compound focus with dedicated recovery segments.',
    template_id: 'tmp_str_ul_v1',
    experience_level: ExperienceLevel.Advanced,
    goal_bucket: GoalBucket.Strength,
  },
  {
    external_id: 'fam_min_equip_db',
    name: 'Minimal Equipment DB-Only Plan',
    description: 'Designed for hotel gyms or limited home setups using only dumbbells.',
    template_id: 'tmp_min_equip_db_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Hypertrophy,
  },
  {
    external_id: 'fam_at_home_bw',
    name: 'Bodyweight Longevity Plan',
    description: 'Zero-equipment training focused on mobility, core, and functional strength.',
    template_id: 'tmp_at_home_bw_v1',
    experience_level: ExperienceLevel.Beginner,
    goal_bucket: GoalBucket.GenFitness,
  },
];
