import { GoalBucket, ExperienceLevel } from '../../types/v1_engine.ts';

const adaptiveFamilies = (['beginner', 'intermediate', 'advanced'] as const).flatMap((exp) => {
  const label = exp === 'beginner' ? 'Beginner' : exp === 'intermediate' ? 'Intermediate' : 'Advanced';
  const level = exp === 'beginner'
    ? ExperienceLevel.Beginner
    : exp === 'intermediate'
      ? ExperienceLevel.Intermediate
      : ExperienceLevel.Advanced;

  return [2, 3, 4, 5, 6].map((days) => ({
    external_id: `fam_adaptive_${exp}_${days}_day`,
    name: `${label} Adaptive ${days}-Day`,
    description: `${label}-appropriate ${days}-day plan structure that honors the user's selected workout frequency while adapting exercises, volume, and intensity to goal, equipment, and injury constraints.`,
    template_id: `tmp_adaptive_${exp}_${days}_day_v1`,
    experience_level: level,
    goal_bucket: GoalBucket.GenFitness,
  }));
});

export const planFamilies = [
  {
    external_id: 'fam_beginner_fb',
    name: 'Beginner Full Body (Standard)',
    description: 'A well-rounded full body program for novices with commercial gym access.',
    template_id: 'tmp_beginner_fb_v1',
    experience_level: ExperienceLevel.Beginner,
    goal_bucket: GoalBucket.GenFitness,
  },
  {
    external_id: 'fam_beginner_machine_fb',
    name: 'Beginner Machine-Focus Full Body',
    description: 'Novice-friendly full body work using machines and dumbbells for maximum safety.',
    template_id: 'tmp_beginner_machine_fb_v1',
    experience_level: ExperienceLevel.Beginner,
    goal_bucket: GoalBucket.GenFitness,
  },
  {
    external_id: 'fam_hyp_fb',
    name: 'Hypertrophy Full Body (3-Day)',
    description: 'Maximum efficiency for muscle growth via high-frequency full body stimulation.',
    template_id: 'tmp_hyp_fb_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Hypertrophy,
  },
  {
    external_id: 'fam_hyp_ul',
    name: 'Hypertrophy Upper/Lower (4-Day)',
    description: 'The industry-standard split for building lean muscle mass.',
    template_id: 'tmp_hyp_ul_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Hypertrophy,
  },
  {
    external_id: 'fam_hyp_ppl',
    name: 'Hypertrophy PPL (6-Day)',
    description: 'High volume bodybuilding split for advanced trainees.',
    template_id: 'tmp_hyp_ppl_v1',
    experience_level: ExperienceLevel.Advanced,
    goal_bucket: GoalBucket.Hypertrophy,
  },
  {
    external_id: 'fam_hyp_5_day',
    name: 'Hypertrophy PPL-UL (5-Day)',
    description: 'The optimal 5-day split for advanced hypertrophy, combining PPL frequency with UL specialization.',
    template_id: 'tmp_hyp_5_day_v1',
    experience_level: ExperienceLevel.Advanced,
    goal_bucket: GoalBucket.Hypertrophy,
  },
  {
    external_id: 'fam_fatloss_fb',
    name: 'Metabolic Fat Loss Full Body',
    description: 'Preserve muscle while maximizing caloric burn through high-density work.',
    template_id: 'tmp_fatloss_fb_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.FatLoss,
  },
  {
    external_id: 'fam_str_fb',
    name: 'Strength Full Body (3-Day)',
    description: 'Barbell-focused strength development for those on a tight schedule.',
    template_id: 'tmp_str_fb_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Strength,
  },
  {
    external_id: 'fam_str_ul',
    name: 'Strength Upper/Lower (4-Day)',
    description: 'Heavy compound focus with dedicated recovery segments.',
    template_id: 'tmp_str_ul_v1',
    experience_level: ExperienceLevel.Advanced,
    goal_bucket: GoalBucket.Strength,
  },
  {
    external_id: 'fam_min_equip_db',
    name: 'Minimal Equipment DB-Only Plan',
    description: 'Designed for hotel gyms or limited home setups using only dumbbells.',
    template_id: 'tmp_min_equip_db_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Hypertrophy,
  },
  {
    external_id: 'fam_at_home_bw',
    name: 'Bodyweight Longevity Plan',
    description: 'Zero-equipment training focused on mobility, core, and functional strength.',
    template_id: 'tmp_at_home_bw_v1',
    experience_level: ExperienceLevel.Beginner,
    goal_bucket: GoalBucket.GenFitness,
  },
  {
    external_id: 'fam_hyp_2_day',
    name: 'Hypertrophy Full Body (2-Day)',
    description: 'A higher-intensity full body split for building mass on a busy schedule.',
    template_id: 'tmp_hyp_2_day_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Hypertrophy,
  },
  {
    external_id: 'fam_str_2_day',
    name: 'Strength Full Body (2-Day)',
    description: 'Heavy compound focus with high recovery for maximum force production.',
    template_id: 'tmp_str_2_day_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Strength,
  },
  {
    external_id: 'fam_gen_2_day',
    name: 'General Fitness FB (2-Day)',
    description: 'Balanced strength and conditioning for general health and metabolic longevity.',
    template_id: 'tmp_gen_2_day_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.GenFitness,
  },
  {
    external_id: 'fam_minimalist_2_day',
    name: 'Minimalist Full Body (2-Day)',
    description: 'A focused, high-standard 2-day plan with proven compound exercises and zero clutter.',
    template_id: 'tmp_minimalist_2_day_v1',
    experience_level: ExperienceLevel.Beginner,
    goal_bucket: GoalBucket.GenFitness,
  },
  {
    external_id: 'fam_minimalist_2_day_strength',
    name: 'Minimalist Strength (2-Day)',
    description: 'Strength-biased fully body setup focusing on heavy compound force production.',
    template_id: 'tmp_minimalist_2_day_strength_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Strength,
  },
  {
    external_id: 'fam_minimalist_2_day_aesthetics',
    name: 'Minimalist Aesthetics (2-Day)',
    description: 'Hypertrophy-biased full body structure to build muscle efficiently across two sessions.',
    template_id: 'tmp_minimalist_2_day_aesthetics_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Hypertrophy,
  },
  {
    external_id: 'fam_minimalist_2_day_athletic',
    name: 'Minimalist Performance (2-Day)',
    description: 'Athleticism-biased plan prioritizing power, agility, and overall functional performance.',
    template_id: 'tmp_minimalist_2_day_athletic_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Athletic,
  },
  {
    external_id: 'fam_str_5_day',
    name: 'Strength PPL-UL (5-Day)',
    description: 'Advanced powerbuilding structure for maximizing multi-joint lifting capacity.',
    template_id: 'tmp_str_5_day_v1',
    experience_level: ExperienceLevel.Advanced,
    goal_bucket: GoalBucket.Strength,
  },
  {
    external_id: 'fam_recomp_fb',
    name: 'Body Recomposition FB (3-Day)',
    description: 'Optimize muscle retention while burning fat through metabolic density.',
    template_id: 'tmp_fatloss_fb_v1', // Using fatloss/hyp hybrid logic
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Recomp,
  },
  {
    external_id: 'fam_recomp_ul',
    name: 'Body Recomposition UL (4-Day)',
    description: 'High-frequency muscle stimulation combined with calculated volume management.',
    template_id: 'tmp_hyp_ul_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Recomp,
  },
  {
    external_id: 'fam_athletic_ul',
    name: 'Athletic Performance UL (4-Day)',
    description: 'A performance-focused split designed to build explosive power and functional strength.',
    template_id: 'tmp_athletic_ul_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Athletic,
  },
  {
    external_id: 'fam_fatloss_ul',
    name: 'Metabolic Fat Loss UL (4-Day)',
    description: 'High-density sessions designed to maximize caloric burn while preserving lean muscle.',
    template_id: 'tmp_fatloss_ul_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.FatLoss,
  },
  {
    external_id: 'fam_db_only_ul',
    name: 'DB-Only Performance UL (4-Day)',
    description: 'Professional-grade training using only dumbbells, ideal for hotel or home setups.',
    template_id: 'tmp_db_only_ul_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.Hypertrophy,
  },
  {
    external_id: 'fam_bw_skill_ul',
    name: 'Bodyweight Skill UL (4-Day)',
    description: 'Master advanced calisthenics skills through a structured upper/lower progression.',
    template_id: 'tmp_bw_skill_ul_v1',
    experience_level: ExperienceLevel.Intermediate,
    goal_bucket: GoalBucket.GenFitness,
  },
  ...adaptiveFamilies,
];
