import { coreExercises } from './exercises';
import { coreTemplates } from './templates';
import { planFamilies } from './families';
import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';

// Helper to escape strings for SQL
function escapeSQL(val: string): string {
  return val.replace(/'/g, "''");
}

function generateSQL() {
  const sqlLines: string[] = [];
  
  sqlLines.push('-- =========================================');
  sqlLines.push('-- METRIQFIT V1 SEED DATA');
  sqlLines.push('-- AUTO-GENERATED BY loaders/seeds/to_sql.ts');
  sqlLines.push('-- =========================================\n');

  // 1. Wipe tables (cascading deletes where applicable)
  sqlLines.push('TRUNCATE table public.v1_exercises CASCADE;');
  sqlLines.push('TRUNCATE table public.v1_plan_families CASCADE;');
  sqlLines.push('TRUNCATE table public.v1_templates CASCADE;');
  sqlLines.push('TRUNCATE table public.v1_workout_days CASCADE;');
  sqlLines.push('TRUNCATE table public.v1_template_slots CASCADE;\n');

  // 2. Insert Exercises
  sqlLines.push('-- =========================================');
  sqlLines.push('-- EXERCISES');
  sqlLines.push('-- =========================================\n');
  
  for (const ex of coreExercises) {
    const exId = crypto.randomUUID();
    const progressionTypes = (ex.progression_types || []).join(',');
    const contraindications = (ex.contraindications || []).join(',');
    
    sqlLines.push(
      `INSERT INTO public.v1_exercises (id, external_id, name, movement_pattern, architectural_group, equipment_category, is_unilateral, setup_complexity, fatigue_cost, tier, progression_types, contraindications, estimated_duration_seconds) ` +
      `VALUES ('${exId}', '${ex.external_id}', '${escapeSQL(ex.name)}', '${ex.movement_pattern}', '${ex.architectural_group}', '${ex.equipment_category}', ${ex.is_unilateral}, '${ex.setup_complexity}', '${ex.fatigue_cost}', '${ex.tier}', ` +
      `'{${progressionTypes}}', '{${contraindications}}', ${ex.estimated_duration_seconds || 60});`
    );
  }
  
  // 3. Insert Families and Templates
  sqlLines.push('\n-- =========================================');
  sqlLines.push('-- FAMILIES AND TEMPLATES');
  sqlLines.push('-- =========================================\n');

  const templateMap = new Map();
  for (const tmp of coreTemplates) {
    templateMap.set(tmp.external_id, tmp);
  }

  for (const fam of planFamilies) {
    const famId = crypto.randomUUID();
    const tmp = templateMap.get(fam.template_id);
    
    const trainingStyle = tmp?.training_style || 'full_body';
    const liftComfort = 'barbell'; // Default
    const environment = 'commercial_gym'; // Default
    const progressionModel = 'linear_progression'; // Default

    sqlLines.push(
      `INSERT INTO public.v1_plan_families (id, external_id, name, goal_bucket, training_style, days_per_week, lift_comfort, environment, progression_model) ` +
      `VALUES ('${famId}', '${fam.external_id}', '${escapeSQL(fam.name)}', '${fam.goal_bucket}', '${trainingStyle}', ${tmp?.days.length || 3}, '${liftComfort}', '${environment}', '${progressionModel}');`
    );

    if (tmp) {
      const tmpId = crypto.randomUUID();
      sqlLines.push(
        `INSERT INTO public.v1_templates (id, family_id, external_id, name, block_number, difficulty_score) ` +
        `VALUES ('${tmpId}', '${famId}', '${tmp.external_id}', '${escapeSQL(tmp.name)}', 1, 50);`
      );

      for (const day of tmp.days) {
        const dayId = crypto.randomUUID();
        sqlLines.push(
          `INSERT INTO public.v1_workout_days (id, template_id, day_number, day_type) ` +
          `VALUES ('${dayId}', '${tmpId}', ${day.day_number}, '${day.day_type}');`
        );

        for (const slot of day.slots) {
          const slotId = crypto.randomUUID();
          sqlLines.push(
            `INSERT INTO public.v1_template_slots (id, workout_day_id, order_index, architectural_group, is_required, archetype, progression_model, sets, reps_min, reps_max, target_rpe, rest_seconds) ` +
            `VALUES ('${slotId}', '${dayId}', ${slot.order_index}, '${slot.architectural_group}', ${slot.is_required}, '${slot.archetype}', '${slot.progression_model}', ${slot.sets}, ${slot.reps_min}, ${slot.reps_max}, ${slot.target_rpe}, ${slot.rest_seconds});`
          );
        }
      }
    } else {
      console.warn(`⚠️ Warning: Template not found for family ${fam.external_id}: ${fam.template_id}`);
    }
  }

  const outPath = path.resolve(__dirname, '../../supabase/seed.sql');
  if (!fs.existsSync(path.dirname(outPath))) {
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
  }
  
  fs.writeFileSync(outPath, sqlLines.join('\n'), 'utf-8');
  console.log(`✅ Successfully generated seed SQL at: ${outPath}`);
}

generateSQL();
