-- MetriqFit Exercise Seed Data
-- Migration 006: Seed 175 exercises from source-of-truth
-- Source: app_ready_programs_175_v3_constraints.json

-- ===========================================
-- SEED EXERCISES (175 total)
-- ===========================================
INSERT INTO public.exercises (external_id, name, category, equipment_required, primary_muscle, pattern, difficulty, is_compound)
VALUES
  -- Lower Body (ex_001 - ex_043)
  ('ex_001', 'Back Squat', 'Lower Body', ARRAY['freeweight_or_machine'], 'quads', 'squat', 'beginner', true),
  ('ex_002', 'Back Squat Paused', 'Lower Body', ARRAY['freeweight_or_machine'], 'quads', 'squat', 'advanced', true),
  ('ex_003', 'Front Squat', 'Lower Body', ARRAY['barbell'], 'quads', 'squat', 'intermediate', true),
  ('ex_004', 'Goblet Squat', 'Lower Body', ARRAY['dumbbell', 'kettlebell'], 'quads', 'squat', 'beginner', true),
  ('ex_005', 'Safety-Bar Squat', 'Lower Body', ARRAY['barbell'], 'quads', 'squat', 'beginner', true),
  ('ex_006', 'Zercher Squat', 'Lower Body', ARRAY['barbell'], 'quads', 'squat', 'intermediate', true),
  ('ex_007', 'Conventional Deadlift', 'Lower Body', ARRAY['barbell'], 'posterior_chain', 'hinge', 'intermediate', true),
  ('ex_008', 'Sumo Deadlift', 'Lower Body', ARRAY['barbell'], 'posterior_chain', 'hinge', 'intermediate', true),
  ('ex_009', 'Trap-Bar Deadlift', 'Lower Body', ARRAY['barbell'], 'posterior_chain', 'hinge', 'beginner', true),
  ('ex_010', 'Romanian Deadlift', 'Lower Body', ARRAY['freeweight_or_machine'], 'hamstrings', 'hinge', 'beginner', true),
  ('ex_011', 'Single-Leg Romanian Deadlift', 'Lower Body', ARRAY['freeweight_or_machine'], 'hamstrings', 'unilateral_lower', 'intermediate', true),
  ('ex_012', 'Dumbbell Romanian Deadlift', 'Lower Body', ARRAY['dumbbell'], 'hamstrings', 'hinge', 'beginner', true),
  ('ex_013', 'Barbell Hip Thrust', 'Lower Body', ARRAY['barbell'], 'glutes', 'hinge', 'beginner', true),
  ('ex_014', 'Machine Hip Thrust', 'Lower Body', ARRAY['machine'], 'glutes', 'glute_isolation', 'beginner', false),
  ('ex_015', 'Dumbbell Hip Thrust', 'Lower Body', ARRAY['dumbbell'], 'glutes', 'glute_isolation', 'beginner', false),
  ('ex_016', 'Cable Pull-Through', 'Lower Body', ARRAY['cable'], 'glutes', 'hinge', 'beginner', true),
  ('ex_017', 'Kettlebell Swing', 'Lower Body', ARRAY['kettlebell'], 'glutes', 'hinge', 'beginner', true),
  ('ex_018', 'Bulgarian Split Squat', 'Lower Body', ARRAY['freeweight_or_machine'], 'quads', 'unilateral_lower', 'intermediate', true),
  ('ex_019', 'Rear-Foot-Elevated Split Squat', 'Lower Body', ARRAY['freeweight_or_machine'], 'quads', 'unilateral_lower', 'intermediate', true),
  ('ex_020', 'Walking Lunge', 'Lower Body', ARRAY['freeweight_or_machine'], 'quads', 'unilateral_lower', 'beginner', true),
  ('ex_021', 'Reverse Lunge', 'Lower Body', ARRAY['freeweight_or_machine'], 'quads', 'unilateral_lower', 'beginner', true),
  ('ex_022', 'Step-Up', 'Lower Body', ARRAY['freeweight_or_machine'], 'quads', 'unilateral_lower', 'beginner', true),
  ('ex_023', 'Leg Press', 'Lower Body', ARRAY['machine'], 'quads', 'squat', 'beginner', true),
  ('ex_024', 'Hack Squat', 'Lower Body', ARRAY['machine'], 'quads', 'squat', 'beginner', true),
  ('ex_025', 'Belt Squat', 'Lower Body', ARRAY['machine'], 'quads', 'squat', 'beginner', true),
  ('ex_026', 'Pendulum Squat', 'Lower Body', ARRAY['machine'], 'quads', 'squat', 'beginner', true),
  ('ex_027', 'Leg Extension', 'Lower Body', ARRAY['machine'], 'quads', 'knee_isolation', 'beginner', false),
  ('ex_028', 'Lying Leg Curl', 'Lower Body', ARRAY['machine'], 'hamstrings', 'ham_isolation', 'beginner', false),
  ('ex_029', 'Seated Leg Curl', 'Lower Body', ARRAY['machine'], 'hamstrings', 'ham_isolation', 'beginner', false),
  ('ex_030', 'Glute-Ham Raise', 'Lower Body', ARRAY['bodyweight'], 'hamstrings', 'ham_isolation', 'intermediate', false),
  ('ex_031', 'Nordic Curl', 'Lower Body', ARRAY['bodyweight'], 'hamstrings', 'ham_isolation', 'advanced', false),
  ('ex_032', 'Hip Abduction Machine', 'Lower Body', ARRAY['machine'], 'glutes', 'glute_isolation', 'beginner', false),
  ('ex_033', 'Hip Adduction Machine', 'Lower Body', ARRAY['machine'], 'adductors', 'glute_isolation', 'beginner', false),
  ('ex_034', 'Cable Kickback', 'Lower Body', ARRAY['cable'], 'glutes', 'glute_isolation', 'beginner', false),
  ('ex_035', 'Smith Machine Squat', 'Lower Body', ARRAY['smith_machine'], 'quads', 'squat', 'beginner', true),
  ('ex_036', 'V-Squat / Pendulum Squat', 'Lower Body', ARRAY['machine'], 'quads', 'squat', 'beginner', true),
  ('ex_037', 'Box Squat', 'Lower Body', ARRAY['freeweight_or_machine'], 'quads', 'squat', 'intermediate', true),
  ('ex_038', 'Sissy Squat', 'Lower Body', ARRAY['bodyweight'], 'quads', 'knee_isolation', 'beginner', false),
  ('ex_039', 'Bodyweight Squat', 'Lower Body', ARRAY['bodyweight'], 'quads', 'squat', 'beginner', true),
  ('ex_040', 'Pistol Squat', 'Lower Body', ARRAY['bodyweight'], 'quads', 'unilateral_lower', 'advanced', true),
  ('ex_041', 'Landmine Squat', 'Lower Body', ARRAY['barbell'], 'quads', 'squat', 'beginner', true),
  ('ex_042', 'Standing Calf Raise', 'Lower Body', ARRAY['freeweight_or_machine'], 'calves', 'calves', 'beginner', false),
  ('ex_043', 'Seated Calf Raise', 'Lower Body', ARRAY['freeweight_or_machine'], 'calves', 'calves', 'beginner', false),
  ('ex_044', 'Donkey Calf Raise', 'Lower Body', ARRAY['machine'], 'calves', 'calves', 'beginner', false),
  ('ex_045', 'Single-Leg Calf Raise', 'Lower Body', ARRAY['freeweight_or_machine'], 'calves', 'calves', 'beginner', false),
  ('ex_046', 'Stiff-Leg Deadlift', 'Lower Body', ARRAY['freeweight_or_machine'], 'hamstrings', 'hinge', 'beginner', true),
  ('ex_047', 'Good Morning', 'Lower Body', ARRAY['barbell'], 'hamstrings', 'hinge', 'intermediate', true),

  -- Chest / Push (ex_048 - ex_066)
  ('ex_048', 'Flat Barbell Bench Press', 'Chest / Push', ARRAY['barbell'], 'chest', 'horizontal_push', 'beginner', true),
  ('ex_049', 'Flat Barbell Bench Press Paused', 'Chest / Push', ARRAY['barbell'], 'chest', 'horizontal_push', 'intermediate', true),
  ('ex_050', 'Incline Barbell Bench Press', 'Chest / Push', ARRAY['barbell'], 'chest', 'horizontal_push', 'beginner', true),
  ('ex_051', 'Close-Grip Bench Press', 'Chest / Push', ARRAY['barbell'], 'triceps', 'horizontal_push', 'beginner', true),
  ('ex_052', 'Flat Dumbbell Bench Press', 'Chest / Push', ARRAY['dumbbell'], 'chest', 'horizontal_push', 'beginner', true),
  ('ex_053', 'Incline Dumbbell Bench Press', 'Chest / Push', ARRAY['dumbbell'], 'chest', 'horizontal_push', 'beginner', true),
  ('ex_054', 'Neutral-Grip Dumbbell Press', 'Chest / Push', ARRAY['dumbbell'], 'chest', 'horizontal_push', 'beginner', true),
  ('ex_055', 'Machine Chest Press', 'Chest / Push', ARRAY['machine'], 'chest', 'horizontal_push', 'beginner', true),
  ('ex_056', 'Incline Machine Press', 'Chest / Push', ARRAY['machine'], 'chest', 'horizontal_push', 'beginner', true),
  ('ex_057', 'Smith Machine Bench Press', 'Chest / Push', ARRAY['smith_machine'], 'chest', 'horizontal_push', 'beginner', true),
  ('ex_058', 'Push-Up', 'Chest / Push', ARRAY['bodyweight'], 'chest', 'horizontal_push', 'beginner', true),
  ('ex_059', 'Push-Up (Weighted)', 'Chest / Push', ARRAY['bodyweight'], 'chest', 'horizontal_push', 'intermediate', true),
  ('ex_060', 'Dip (Chest Focus)', 'Chest / Push', ARRAY['bodyweight'], 'chest', 'horizontal_push', 'beginner', true),
  ('ex_061', 'Dip (Weighted)', 'Chest / Push', ARRAY['bodyweight'], 'chest', 'horizontal_push', 'intermediate', true),
  ('ex_062', 'Cable Flye (Low-to-High)', 'Chest / Push', ARRAY['cable'], 'chest', 'chest_isolation', 'beginner', false),
  ('ex_063', 'Cable Flye (High-to-Low)', 'Chest / Push', ARRAY['cable'], 'chest', 'chest_isolation', 'beginner', false),
  ('ex_064', 'Cable Flye (Mid)', 'Chest / Push', ARRAY['cable'], 'chest', 'chest_isolation', 'beginner', false),
  ('ex_065', 'Dumbbell Flye', 'Chest / Push', ARRAY['dumbbell'], 'chest', 'chest_isolation', 'beginner', false),
  ('ex_066', 'Pec Deck Flye', 'Chest / Push', ARRAY['machine'], 'chest', 'chest_isolation', 'beginner', false),

  -- Chest / Push (continued) - ex_067
  ('ex_067', 'Dumbbell Pullover', 'Chest / Push', ARRAY['dumbbell'], 'chest', 'chest_isolation', 'beginner', false),

  -- Back / Pull (ex_068 - ex_110)
  ('ex_068', 'Barbell Bent-Over Row', 'Back / Pull', ARRAY['barbell'], 'lats', 'horizontal_pull', 'intermediate', true),
  ('ex_069', 'Pendlay Row', 'Back / Pull', ARRAY['barbell'], 'lats', 'horizontal_pull', 'intermediate', true),
  ('ex_070', 'Dumbbell Row', 'Back / Pull', ARRAY['dumbbell'], 'lats', 'horizontal_pull', 'beginner', true),
  ('ex_071', 'Dumbbell Row (Chest-Supported)', 'Back / Pull', ARRAY['dumbbell'], 'lats', 'horizontal_pull', 'beginner', true),
  ('ex_072', 'Kroc Row', 'Back / Pull', ARRAY['dumbbell'], 'lats', 'horizontal_pull', 'intermediate', true),
  ('ex_073', 'T-Bar Row', 'Back / Pull', ARRAY['barbell'], 'lats', 'horizontal_pull', 'beginner', true),
  ('ex_074', 'Landmine Row', 'Back / Pull', ARRAY['barbell'], 'lats', 'horizontal_pull', 'beginner', true),
  ('ex_075', 'Seated Cable Row', 'Back / Pull', ARRAY['cable'], 'lats', 'horizontal_pull', 'beginner', true),
  ('ex_076', 'Seated Cable Row (Wide-Grip)', 'Back / Pull', ARRAY['cable'], 'lats', 'horizontal_pull', 'beginner', true),
  ('ex_077', 'Machine Row', 'Back / Pull', ARRAY['machine'], 'lats', 'horizontal_pull', 'beginner', true),
  ('ex_078', 'Machine Row (Chest-Supported)', 'Back / Pull', ARRAY['machine'], 'lats', 'horizontal_pull', 'beginner', true),
  ('ex_079', 'Pull-Up', 'Back / Pull', ARRAY['bodyweight'], 'lats', 'vertical_pull', 'intermediate', true),
  ('ex_080', 'Pull-Up (Weighted)', 'Back / Pull', ARRAY['bodyweight'], 'lats', 'vertical_pull', 'advanced', true),
  ('ex_081', 'Chin-Up', 'Back / Pull', ARRAY['bodyweight'], 'lats', 'vertical_pull', 'intermediate', true),
  ('ex_082', 'Chin-Up (Weighted)', 'Back / Pull', ARRAY['bodyweight'], 'lats', 'vertical_pull', 'advanced', true),
  ('ex_083', 'Neutral-Grip Pull-Up', 'Back / Pull', ARRAY['bodyweight'], 'lats', 'vertical_pull', 'intermediate', true),
  ('ex_084', 'Lat Pulldown (Wide-Grip)', 'Back / Pull', ARRAY['cable'], 'lats', 'vertical_pull', 'beginner', true),
  ('ex_085', 'Lat Pulldown (Close-Grip)', 'Back / Pull', ARRAY['cable'], 'lats', 'vertical_pull', 'beginner', true),
  ('ex_086', 'Lat Pulldown (Neutral-Grip)', 'Back / Pull', ARRAY['cable'], 'lats', 'vertical_pull', 'beginner', true),
  ('ex_087', 'Lat Pulldown (Underhand)', 'Back / Pull', ARRAY['cable'], 'lats', 'vertical_pull', 'beginner', true),
  ('ex_088', 'Assisted Pull-Up Machine', 'Back / Pull', ARRAY['machine'], 'lats', 'vertical_pull', 'beginner', true),
  ('ex_089', 'Chest-Supported DB Row', 'Back / Pull', ARRAY['dumbbell'], 'lats', 'horizontal_pull', 'beginner', true),
  ('ex_090', 'Seal Row', 'Back / Pull', ARRAY['barbell', 'dumbbell'], 'lats', 'horizontal_pull', 'intermediate', true),
  ('ex_091', 'Meadows Row', 'Back / Pull', ARRAY['barbell'], 'lats', 'horizontal_pull', 'intermediate', true),
  ('ex_092', 'Inverted Row', 'Back / Pull', ARRAY['bodyweight'], 'lats', 'horizontal_pull', 'beginner', true),
  ('ex_093', 'Straight-Arm Pulldown', 'Back / Pull', ARRAY['cable'], 'lats', 'vertical_pull', 'beginner', false),
  ('ex_094', 'Machine Pullover', 'Back / Pull', ARRAY['machine'], 'lats', 'vertical_pull', 'beginner', false),
  ('ex_095', 'Cable Pullover', 'Back / Pull', ARRAY['cable'], 'lats', 'vertical_pull', 'beginner', false),
  ('ex_096', 'Bent-Over Dumbbell Row (Bilateral)', 'Back / Pull', ARRAY['dumbbell'], 'lats', 'horizontal_pull', 'beginner', true),
  ('ex_097', 'Dumbbell Pullover', 'Back / Pull', ARRAY['dumbbell'], 'lats', 'vertical_pull', 'beginner', false),
  ('ex_098', 'Barbell Shrug', 'Back / Pull', ARRAY['barbell'], 'traps', 'shrug', 'beginner', false),
  ('ex_099', 'Dumbbell Shrug', 'Back / Pull', ARRAY['dumbbell'], 'traps', 'shrug', 'beginner', false),
  ('ex_100', 'Trap-Bar Shrug', 'Back / Pull', ARRAY['barbell'], 'traps', 'shrug', 'beginner', false),
  ('ex_101', 'Cable Shrug', 'Back / Pull', ARRAY['cable'], 'traps', 'shrug', 'beginner', false),
  ('ex_102', 'Machine Shrug', 'Back / Pull', ARRAY['machine'], 'traps', 'shrug', 'beginner', false),
  ('ex_103', 'Face Pull', 'Back / Pull', ARRAY['cable'], 'rear_delts', 'horizontal_pull', 'beginner', false),
  ('ex_104', 'Reverse Pec Deck', 'Back / Pull', ARRAY['machine'], 'rear_delts', 'rear_delt_isolation', 'beginner', false),
  ('ex_105', 'Band Pull-Apart', 'Back / Pull', ARRAY['band'], 'rear_delts', 'rear_delt_isolation', 'beginner', false),
  ('ex_106', 'Rear Delt Cable Flye', 'Back / Pull', ARRAY['cable'], 'rear_delts', 'rear_delt_isolation', 'beginner', false),
  ('ex_107', 'Bent-Over Rear Delt Flye (DB)', 'Back / Pull', ARRAY['dumbbell'], 'rear_delts', 'rear_delt_isolation', 'beginner', false),
  ('ex_108', 'Rack Pull', 'Back / Pull', ARRAY['barbell'], 'posterior_chain', 'hinge', 'intermediate', true),
  ('ex_109', 'Block Pull', 'Back / Pull', ARRAY['barbell'], 'posterior_chain', 'hinge', 'intermediate', true),
  ('ex_110', 'Deadlift Paused', 'Back / Pull', ARRAY['barbell'], 'posterior_chain', 'hinge', 'advanced', true),

  -- Shoulders (ex_111 - ex_135)
  ('ex_111', 'Standing BB Overhead Press', 'Shoulders', ARRAY['barbell'], 'shoulders', 'vertical_push', 'intermediate', true),
  ('ex_112', 'Seated BB Overhead Press', 'Shoulders', ARRAY['barbell'], 'shoulders', 'vertical_push', 'beginner', true),
  ('ex_113', 'Push Press', 'Shoulders', ARRAY['barbell'], 'shoulders', 'vertical_push', 'intermediate', true),
  ('ex_114', 'Seated Dumbbell Overhead Press', 'Shoulders', ARRAY['dumbbell'], 'shoulders', 'vertical_push', 'beginner', true),
  ('ex_115', 'Standing Dumbbell Overhead Press', 'Shoulders', ARRAY['dumbbell'], 'shoulders', 'vertical_push', 'beginner', true),
  ('ex_116', 'Arnold Press', 'Shoulders', ARRAY['dumbbell'], 'shoulders', 'vertical_push', 'intermediate', true),
  ('ex_117', 'Machine Shoulder Press', 'Shoulders', ARRAY['machine'], 'shoulders', 'vertical_push', 'beginner', true),
  ('ex_118', 'Smith Machine Overhead Press', 'Shoulders', ARRAY['smith_machine'], 'shoulders', 'vertical_push', 'beginner', true),
  ('ex_119', 'Landmine Press', 'Shoulders', ARRAY['barbell'], 'shoulders', 'vertical_push', 'beginner', true),
  ('ex_120', 'Dumbbell Lateral Raise', 'Shoulders', ARRAY['dumbbell'], 'shoulders', 'lateral_raise', 'beginner', false),
  ('ex_121', 'Cable Lateral Raise', 'Shoulders', ARRAY['cable'], 'shoulders', 'lateral_raise', 'beginner', false),
  ('ex_122', 'Machine Lateral Raise', 'Shoulders', ARRAY['machine'], 'shoulders', 'lateral_raise', 'beginner', false),
  ('ex_123', 'Dumbbell Front Raise', 'Shoulders', ARRAY['dumbbell'], 'shoulders', 'front_raise', 'beginner', false),
  ('ex_124', 'Cable Front Raise', 'Shoulders', ARRAY['cable'], 'shoulders', 'front_raise', 'beginner', false),
  ('ex_125', 'Plate Front Raise', 'Shoulders', ARRAY['freeweight_or_machine'], 'shoulders', 'front_raise', 'beginner', false),
  ('ex_126', 'Upright Row (Barbell)', 'Shoulders', ARRAY['barbell'], 'shoulders', 'shoulder_accessory', 'beginner', true),
  ('ex_127', 'Upright Row (Dumbbell)', 'Shoulders', ARRAY['dumbbell'], 'shoulders', 'shoulder_accessory', 'beginner', true),
  ('ex_128', 'Upright Row (Cable)', 'Shoulders', ARRAY['cable'], 'shoulders', 'shoulder_accessory', 'beginner', true),
  ('ex_129', 'Pike Push-Up', 'Shoulders', ARRAY['bodyweight'], 'shoulders', 'vertical_push', 'beginner', true),
  ('ex_130', 'Handstand Push-Up', 'Shoulders', ARRAY['bodyweight'], 'shoulders', 'vertical_push', 'advanced', true),
  ('ex_131', 'Lu Raise', 'Shoulders', ARRAY['freeweight_or_machine'], 'shoulders', 'shoulder_accessory', 'intermediate', false),
  ('ex_132', 'Reverse Flye (Incline Bench)', 'Shoulders', ARRAY['dumbbell'], 'rear_delts', 'rear_delt_isolation', 'beginner', false),
  ('ex_133', 'Cuban Press', 'Shoulders', ARRAY['freeweight_or_machine'], 'shoulders', 'shoulder_accessory', 'intermediate', false),
  ('ex_134', 'Y-Raise (Incline Bench)', 'Shoulders', ARRAY['freeweight_or_machine'], 'shoulders', 'shoulder_accessory', 'intermediate', false),
  ('ex_135', 'External Rotation (Cable/Band)', 'Shoulders', ARRAY['band', 'cable'], 'shoulders', 'shoulder_accessory', 'beginner', false),

  -- Arms / Grip (ex_136 - ex_160)
  ('ex_136', 'Dumbbell Biceps Curl', 'Arms / Grip', ARRAY['dumbbell'], 'biceps', 'biceps', 'beginner', false),
  ('ex_137', 'Alternating Dumbbell Curl', 'Arms / Grip', ARRAY['dumbbell'], 'biceps', 'biceps', 'beginner', false),
  ('ex_138', 'Barbell Curl', 'Arms / Grip', ARRAY['barbell'], 'biceps', 'biceps', 'intermediate', false),
  ('ex_139', 'EZ-Bar Curl', 'Arms / Grip', ARRAY['barbell'], 'biceps', 'biceps', 'beginner', false),
  ('ex_140', 'Hammer Curl', 'Arms / Grip', ARRAY['freeweight_or_machine'], 'biceps', 'biceps', 'beginner', false),
  ('ex_141', 'Rope Hammer Curl (Cable)', 'Arms / Grip', ARRAY['cable'], 'biceps', 'biceps', 'beginner', false),
  ('ex_142', 'Incline Dumbbell Curl', 'Arms / Grip', ARRAY['dumbbell'], 'biceps', 'biceps', 'intermediate', false),
  ('ex_143', 'Concentration Curl', 'Arms / Grip', ARRAY['freeweight_or_machine'], 'biceps', 'biceps', 'beginner', false),
  ('ex_144', 'Preacher Curl (EZ-Bar)', 'Arms / Grip', ARRAY['barbell'], 'biceps', 'biceps', 'beginner', false),
  ('ex_145', 'Preacher Curl (Machine)', 'Arms / Grip', ARRAY['machine'], 'biceps', 'biceps', 'beginner', false),
  ('ex_146', 'Cable Curl (Straight Bar)', 'Arms / Grip', ARRAY['cable'], 'biceps', 'biceps', 'beginner', false),
  ('ex_147', 'Cable Curl (Rope)', 'Arms / Grip', ARRAY['cable'], 'biceps', 'biceps', 'beginner', false),
  ('ex_148', 'Triceps Pushdown (Rope)', 'Arms / Grip', ARRAY['freeweight_or_machine'], 'triceps', 'triceps', 'beginner', false),
  ('ex_149', 'Triceps Pushdown (Straight Bar)', 'Arms / Grip', ARRAY['freeweight_or_machine'], 'triceps', 'triceps', 'beginner', false),
  ('ex_150', 'Overhead Cable Triceps Extension', 'Arms / Grip', ARRAY['cable'], 'triceps', 'triceps', 'beginner', false),
  ('ex_151', 'Dumbbell Overhead Triceps Extension', 'Arms / Grip', ARRAY['dumbbell'], 'triceps', 'triceps', 'beginner', false),
  ('ex_152', 'Skull Crushers (EZ-Bar)', 'Arms / Grip', ARRAY['barbell'], 'triceps', 'triceps', 'beginner', false),
  ('ex_153', 'Skull Crushers (Dumbbells)', 'Arms / Grip', ARRAY['dumbbell'], 'triceps', 'triceps', 'beginner', false),
  ('ex_154', 'Triceps Kickback', 'Arms / Grip', ARRAY['freeweight_or_machine'], 'triceps', 'triceps', 'beginner', false),
  ('ex_155', 'JM Press', 'Arms / Grip', ARRAY['freeweight_or_machine'], 'triceps', 'triceps', 'beginner', false),
  ('ex_156', 'Close-Grip Push-Up', 'Arms / Grip', ARRAY['bodyweight'], 'triceps', 'triceps', 'beginner', false),
  ('ex_157', 'Diamond Push-Up', 'Arms / Grip', ARRAY['bodyweight'], 'triceps', 'triceps', 'beginner', false),
  ('ex_158', 'Farmer''s Carry', 'Arms / Grip', ARRAY['freeweight_or_machine'], 'forearms_grip', 'grip_carry', 'beginner', true),
  ('ex_159', 'Dead Hang', 'Arms / Grip', ARRAY['freeweight_or_machine'], 'forearms_grip', 'grip_carry', 'beginner', false),
  ('ex_160', 'Plate Pinch Hold', 'Arms / Grip', ARRAY['freeweight_or_machine'], 'forearms_grip', 'grip_carry', 'beginner', false),

  -- Core (ex_161 - ex_172)
  ('ex_161', 'Plank', 'Core', ARRAY['bodyweight'], 'core', 'anti_extension', 'beginner', false),
  ('ex_162', 'Side Plank', 'Core', ARRAY['bodyweight'], 'core', 'anti_extension', 'beginner', false),
  ('ex_163', 'RKC Plank', 'Core', ARRAY['bodyweight'], 'core', 'anti_extension', 'beginner', false),
  ('ex_164', 'Dead Bug', 'Core', ARRAY['bodyweight'], 'core', 'core_other', 'beginner', false),
  ('ex_165', 'Bird Dog', 'Core', ARRAY['bodyweight'], 'core', 'core_other', 'beginner', false),
  ('ex_166', 'Hanging Knee Raise', 'Core', ARRAY['bodyweight'], 'core', 'hip_flexion', 'beginner', false),
  ('ex_167', 'Hanging Leg Raise', 'Core', ARRAY['bodyweight'], 'core', 'hip_flexion', 'beginner', false),
  ('ex_168', 'Captain''s Chair Knee Raise', 'Core', ARRAY['bodyweight'], 'core', 'core_other', 'beginner', false),
  ('ex_169', 'Cable Crunch', 'Core', ARRAY['cable'], 'core', 'spinal_flexion', 'beginner', false),
  ('ex_170', 'Ab Wheel Rollout', 'Core', ARRAY['bodyweight'], 'core', 'core_other', 'beginner', false),
  ('ex_171', 'Pallof Press', 'Core', ARRAY['bodyweight'], 'core', 'anti_rotation', 'beginner', false),
  ('ex_172', 'Russian Twist', 'Core', ARRAY['bodyweight'], 'core', 'core_other', 'beginner', false),

  -- Cardio / Conditioning (ex_173 - ex_175)
  ('ex_173', 'Treadmill Walking', 'Cardio / Conditioning', ARRAY['cardio_machine'], 'conditioning', 'cardio', 'beginner', false),
  ('ex_174', 'Treadmill Running', 'Cardio / Conditioning', ARRAY['cardio_machine'], 'conditioning', 'cardio', 'beginner', false),
  ('ex_175', 'Stair Climber', 'Cardio / Conditioning', ARRAY['cardio_machine'], 'conditioning', 'cardio', 'beginner', false)

ON CONFLICT (external_id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  equipment_required = EXCLUDED.equipment_required,
  primary_muscle = EXCLUDED.primary_muscle,
  pattern = EXCLUDED.pattern,
  difficulty = EXCLUDED.difficulty,
  is_compound = EXCLUDED.is_compound;

-- Verify count
DO $$
DECLARE
  exercise_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO exercise_count FROM public.exercises;
  RAISE NOTICE 'Seeded % exercises', exercise_count;

  IF exercise_count < 175 THEN
    RAISE WARNING 'Expected 175 exercises, but only % were inserted', exercise_count;
  END IF;
END $$;
