-- MetriqFit Food Items Seed Data
-- Migration 007: Seed ~175 common foods from USDA FoodData Central
-- Purpose: Offline support, faster UX, curated high-quality nutrition data
-- ===========================================
-- SEED FOOD ITEMS (~175 total)
-- ===========================================
INSERT INTO public.food_items (
        name,
        brand,
        category,
        calories_per_100g,
        protein_per_100g,
        carbs_per_100g,
        fat_per_100g,
        fiber_per_100g,
        sugar_per_100g,
        sodium_per_100g,
        serving_size_g,
        serving_description,
        source,
        is_verified
    )
VALUES -- PROTEINS (35 items) - Essential building blocks
    (
        'Chicken Breast (Skinless, Cooked)',
        NULL,
        'Protein',
        165,
        31.0,
        0,
        3.6,
        0,
        0,
        74,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Chicken Thigh (Skinless, Cooked)',
        NULL,
        'Protein',
        209,
        26.0,
        0,
        10.9,
        0,
        0,
        95,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Ground Beef (93% Lean, Cooked)',
        NULL,
        'Protein',
        186,
        26.9,
        0,
        7.7,
        0,
        0,
        72,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Ground Beef (80% Lean, Cooked)',
        NULL,
        'Protein',
        254,
        25.8,
        0,
        16.4,
        0,
        0,
        75,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Sirloin Steak (Cooked)',
        NULL,
        'Protein',
        201,
        28.7,
        0,
        8.5,
        0,
        0,
        60,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Salmon (Atlantic, Cooked)',
        NULL,
        'Protein',
        206,
        22.1,
        0,
        12.4,
        0,
        0,
        59,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Tuna (Canned in Water)',
        NULL,
        'Protein',
        116,
        25.5,
        0,
        0.8,
        0,
        0,
        247,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Tilapia (Cooked)',
        NULL,
        'Protein',
        128,
        26.2,
        0,
        2.7,
        0,
        0,
        56,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Cod (Cooked)',
        NULL,
        'Protein',
        105,
        22.8,
        0,
        0.9,
        0,
        0,
        78,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Shrimp (Cooked)',
        NULL,
        'Protein',
        99,
        20.9,
        0.9,
        1.0,
        0,
        0,
        566,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Eggs (Whole, Cooked)',
        NULL,
        'Protein',
        155,
        12.6,
        1.1,
        10.6,
        0,
        1.1,
        124,
        50,
        'Large egg',
        'usda_fdc',
        true
    ),
    (
        'Egg Whites (Cooked)',
        NULL,
        'Protein',
        52,
        10.9,
        0.7,
        0.2,
        0,
        0.7,
        166,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Turkey Breast (Cooked)',
        NULL,
        'Protein',
        135,
        30.1,
        0,
        0.7,
        0,
        0,
        70,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Ground Turkey (93% Lean, Cooked)',
        NULL,
        'Protein',
        176,
        26.5,
        0,
        7.0,
        0,
        0,
        78,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Pork Chop (Lean, Cooked)',
        NULL,
        'Protein',
        231,
        27.3,
        0,
        12.7,
        0,
        0,
        62,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Pork Tenderloin (Cooked)',
        NULL,
        'Protein',
        143,
        26.2,
        0,
        3.5,
        0,
        0,
        62,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Bacon (Cooked)',
        NULL,
        'Protein',
        541,
        37.0,
        1.4,
        41.8,
        0,
        0,
        1717,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Tofu (Firm)',
        NULL,
        'Protein',
        144,
        15.8,
        3.5,
        8.7,
        2.3,
        0.9,
        14,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Tempeh',
        NULL,
        'Protein',
        193,
        18.5,
        9.4,
        10.8,
        5.7,
        2.2,
        9,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Edamame (Cooked)',
        NULL,
        'Protein',
        122,
        11.2,
        8.9,
        5.2,
        5.2,
        2.2,
        6,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Black Beans (Cooked)',
        NULL,
        'Protein',
        132,
        8.9,
        23.7,
        0.5,
        8.7,
        0.3,
        1,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Chickpeas (Cooked)',
        NULL,
        'Protein',
        164,
        8.9,
        27.4,
        2.6,
        7.6,
        4.8,
        7,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Lentils (Cooked)',
        NULL,
        'Protein',
        116,
        9.0,
        20.1,
        0.4,
        7.9,
        1.8,
        2,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Greek Yogurt (Nonfat, Plain)',
        NULL,
        'Dairy',
        59,
        10.2,
        3.6,
        0.4,
        0,
        3.2,
        36,
        170,
        '1 cup',
        'usda_fdc',
        true
    ),
    (
        'Greek Yogurt (2% Fat, Plain)',
        NULL,
        'Dairy',
        73,
        9.9,
        3.9,
        1.9,
        0,
        3.5,
        35,
        170,
        '1 cup',
        'usda_fdc',
        true
    ),
    (
        'Cottage Cheese (Low-Fat)',
        NULL,
        'Dairy',
        72,
        12.4,
        2.7,
        1.0,
        0,
        2.7,
        364,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Cottage Cheese (Full-Fat)',
        NULL,
        'Dairy',
        98,
        11.1,
        3.4,
        4.3,
        0,
        2.7,
        364,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Whey Protein Powder (Plain)',
        NULL,
        'Supplement',
        375,
        80.0,
        6.7,
        3.3,
        0,
        6.7,
        500,
        30,
        '1 scoop',
        'internal',
        true
    ),
    (
        'Plant Protein Powder (Pea)',
        NULL,
        'Supplement',
        386,
        80.0,
        6.7,
        6.7,
        6.7,
        0,
        1200,
        30,
        '1 scoop',
        'internal',
        true
    ),
    (
        'Protein Bar (Generic)',
        NULL,
        'Supplement',
        380,
        20.0,
        40.0,
        12.0,
        10.0,
        20.0,
        200,
        60,
        '1 bar',
        'internal',
        true
    ),
    (
        'Beef Jerky',
        NULL,
        'Protein',
        410,
        33.2,
        11.1,
        25.6,
        2.3,
        8.3,
        1878,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Deli Turkey (Low Sodium)',
        NULL,
        'Protein',
        107,
        18.3,
        3.8,
        1.7,
        0,
        2.2,
        450,
        56,
        '2 oz',
        'usda_fdc',
        true
    ),
    (
        'Deli Ham (Lean)',
        NULL,
        'Protein',
        145,
        20.9,
        1.5,
        5.5,
        0,
        1.4,
        1203,
        56,
        '2 oz',
        'usda_fdc',
        true
    ),
    (
        'Rotisserie Chicken (Breast)',
        NULL,
        'Protein',
        159,
        29.1,
        0,
        4.2,
        0,
        0,
        392,
        100,
        '100g',
        'internal',
        true
    ),
    (
        'Lamb Chop (Cooked)',
        NULL,
        'Protein',
        294,
        24.5,
        0,
        21.0,
        0,
        0,
        72,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    -- GRAINS & CARBS (25 items) - Energy sources
    (
        'White Rice (Cooked)',
        NULL,
        'Grains',
        130,
        2.7,
        28.2,
        0.3,
        0.4,
        0.1,
        1,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Brown Rice (Cooked)',
        NULL,
        'Grains',
        123,
        2.6,
        25.6,
        1.0,
        1.6,
        0.4,
        5,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Basmati Rice (Cooked)',
        NULL,
        'Grains',
        121,
        2.5,
        25.2,
        0.4,
        0.3,
        0,
        2,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Jasmine Rice (Cooked)',
        NULL,
        'Grains',
        129,
        2.7,
        27.9,
        0.2,
        0.2,
        0,
        1,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Quinoa (Cooked)',
        NULL,
        'Grains',
        120,
        4.4,
        21.3,
        1.9,
        2.8,
        0.9,
        7,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Pasta (Cooked)',
        NULL,
        'Grains',
        131,
        5.0,
        25.1,
        1.1,
        1.8,
        0.6,
        1,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Whole Wheat Pasta (Cooked)',
        NULL,
        'Grains',
        124,
        5.3,
        26.5,
        0.5,
        3.9,
        0.8,
        3,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Oatmeal (Cooked)',
        NULL,
        'Grains',
        71,
        2.5,
        12.0,
        1.5,
        1.7,
        0.4,
        49,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Instant Oats (Dry)',
        NULL,
        'Grains',
        379,
        13.2,
        67.7,
        6.9,
        10.1,
        1.0,
        6,
        40,
        '1/2 cup',
        'usda_fdc',
        true
    ),
    (
        'White Bread',
        NULL,
        'Grains',
        266,
        7.6,
        49.4,
        3.3,
        2.4,
        5.3,
        477,
        28,
        '1 slice',
        'usda_fdc',
        true
    ),
    (
        'Whole Wheat Bread',
        NULL,
        'Grains',
        247,
        12.5,
        41.3,
        3.4,
        6.8,
        5.6,
        443,
        28,
        '1 slice',
        'usda_fdc',
        true
    ),
    (
        'Sourdough Bread',
        NULL,
        'Grains',
        271,
        9.0,
        52.7,
        2.1,
        2.4,
        2.7,
        594,
        28,
        '1 slice',
        'usda_fdc',
        true
    ),
    (
        'Bagel (Plain)',
        NULL,
        'Grains',
        257,
        10.0,
        50.9,
        1.7,
        2.3,
        5.3,
        430,
        85,
        '1 bagel',
        'usda_fdc',
        true
    ),
    (
        'English Muffin',
        NULL,
        'Grains',
        235,
        7.6,
        46.1,
        2.2,
        2.6,
        3.0,
        420,
        57,
        '1 muffin',
        'usda_fdc',
        true
    ),
    (
        'Tortilla (Flour)',
        NULL,
        'Grains',
        304,
        8.0,
        50.7,
        7.3,
        2.7,
        2.7,
        574,
        49,
        '1 tortilla',
        'usda_fdc',
        true
    ),
    (
        'Tortilla (Corn)',
        NULL,
        'Grains',
        218,
        5.7,
        44.6,
        2.8,
        5.7,
        1.1,
        42,
        24,
        '1 tortilla',
        'usda_fdc',
        true
    ),
    (
        'Pita Bread (Whole Wheat)',
        NULL,
        'Grains',
        262,
        9.8,
        50.5,
        2.9,
        6.8,
        1.9,
        415,
        64,
        '1 pita',
        'usda_fdc',
        true
    ),
    (
        'Sweet Potato (Baked)',
        NULL,
        'Vegetables',
        90,
        2.0,
        20.7,
        0.2,
        3.3,
        6.5,
        36,
        130,
        '1 medium',
        'usda_fdc',
        true
    ),
    (
        'White Potato (Baked)',
        NULL,
        'Vegetables',
        93,
        2.5,
        21.2,
        0.1,
        2.2,
        1.2,
        6,
        173,
        '1 medium',
        'usda_fdc',
        true
    ),
    (
        'Red Potato (Boiled)',
        NULL,
        'Vegetables',
        89,
        1.9,
        20.1,
        0.1,
        1.8,
        1.3,
        7,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Couscous (Cooked)',
        NULL,
        'Grains',
        112,
        3.8,
        23.2,
        0.2,
        1.4,
        0.1,
        5,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Barley (Cooked)',
        NULL,
        'Grains',
        123,
        2.3,
        28.2,
        0.4,
        3.8,
        0.3,
        3,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Farro (Cooked)',
        NULL,
        'Grains',
        110,
        5.0,
        26.0,
        0.5,
        3.0,
        0,
        5,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Buckwheat (Cooked)',
        NULL,
        'Grains',
        92,
        3.4,
        19.9,
        0.6,
        2.7,
        0.9,
        4,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Rice Cakes (Plain)',
        NULL,
        'Grains',
        387,
        8.0,
        81.5,
        2.8,
        2.2,
        1.9,
        29,
        9,
        '1 cake',
        'usda_fdc',
        true
    ),
    -- VEGETABLES (25 items) - Micronutrients & fiber
    (
        'Broccoli (Cooked)',
        NULL,
        'Vegetables',
        35,
        2.4,
        7.2,
        0.4,
        3.3,
        1.4,
        33,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Spinach (Raw)',
        NULL,
        'Vegetables',
        23,
        2.9,
        3.6,
        0.4,
        2.2,
        0.4,
        79,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Spinach (Cooked)',
        NULL,
        'Vegetables',
        23,
        3.0,
        3.8,
        0.3,
        2.4,
        0.4,
        70,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Kale (Raw)',
        NULL,
        'Vegetables',
        35,
        2.9,
        4.4,
        1.5,
        4.1,
        0.8,
        53,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Carrots (Raw)',
        NULL,
        'Vegetables',
        41,
        0.9,
        9.6,
        0.2,
        2.8,
        4.7,
        69,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Bell Pepper (Red, Raw)',
        NULL,
        'Vegetables',
        31,
        1.0,
        6.0,
        0.3,
        2.1,
        4.2,
        4,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Bell Pepper (Green, Raw)',
        NULL,
        'Vegetables',
        20,
        0.9,
        4.6,
        0.2,
        1.7,
        2.4,
        3,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Tomato (Raw)',
        NULL,
        'Vegetables',
        18,
        0.9,
        3.9,
        0.2,
        1.2,
        2.6,
        5,
        123,
        '1 medium',
        'usda_fdc',
        true
    ),
    (
        'Cherry Tomatoes',
        NULL,
        'Vegetables',
        18,
        0.9,
        3.9,
        0.2,
        1.2,
        2.6,
        5,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Cucumber (Raw)',
        NULL,
        'Vegetables',
        15,
        0.7,
        3.6,
        0.1,
        0.5,
        1.7,
        2,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Lettuce (Romaine)',
        NULL,
        'Vegetables',
        17,
        1.2,
        3.3,
        0.3,
        2.1,
        1.2,
        8,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Lettuce (Iceberg)',
        NULL,
        'Vegetables',
        14,
        0.9,
        3.0,
        0.1,
        1.2,
        1.9,
        10,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Asparagus (Cooked)',
        NULL,
        'Vegetables',
        22,
        2.4,
        4.1,
        0.2,
        2.1,
        1.3,
        14,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Green Beans (Cooked)',
        NULL,
        'Vegetables',
        35,
        1.8,
        7.9,
        0.1,
        3.4,
        1.4,
        1,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Cauliflower (Cooked)',
        NULL,
        'Vegetables',
        23,
        1.8,
        4.1,
        0.5,
        2.3,
        2.1,
        15,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Brussels Sprouts (Cooked)',
        NULL,
        'Vegetables',
        36,
        2.6,
        7.1,
        0.5,
        3.4,
        2.2,
        16,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Zucchini (Cooked)',
        NULL,
        'Vegetables',
        17,
        1.2,
        3.1,
        0.3,
        1.1,
        1.7,
        3,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Mushrooms (Cooked)',
        NULL,
        'Vegetables',
        28,
        3.3,
        5.3,
        0.5,
        2.2,
        2.3,
        6,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Onion (Raw)',
        NULL,
        'Vegetables',
        40,
        1.1,
        9.3,
        0.1,
        1.7,
        4.2,
        4,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Garlic (Raw)',
        NULL,
        'Vegetables',
        149,
        6.4,
        33.1,
        0.5,
        2.1,
        1.0,
        17,
        3,
        '1 clove',
        'usda_fdc',
        true
    ),
    (
        'Celery (Raw)',
        NULL,
        'Vegetables',
        14,
        0.7,
        3.0,
        0.2,
        1.6,
        1.3,
        80,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Eggplant (Cooked)',
        NULL,
        'Vegetables',
        35,
        0.8,
        8.7,
        0.2,
        2.5,
        3.2,
        1,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Cabbage (Raw)',
        NULL,
        'Vegetables',
        25,
        1.3,
        5.8,
        0.1,
        2.5,
        3.2,
        18,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Bok Choy (Cooked)',
        NULL,
        'Vegetables',
        12,
        1.6,
        1.8,
        0.2,
        1.0,
        0.8,
        65,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Mixed Greens (Salad)',
        NULL,
        'Vegetables',
        15,
        1.3,
        2.4,
        0.2,
        1.5,
        0.8,
        25,
        100,
        '100g',
        'internal',
        true
    ),
    -- FRUITS (20 items) - Natural sugars & vitamins
    (
        'Banana',
        NULL,
        'Fruits',
        89,
        1.1,
        22.8,
        0.3,
        2.6,
        12.2,
        1,
        118,
        '1 medium',
        'usda_fdc',
        true
    ),
    (
        'Apple (With Skin)',
        NULL,
        'Fruits',
        52,
        0.3,
        13.8,
        0.2,
        2.4,
        10.4,
        1,
        182,
        '1 medium',
        'usda_fdc',
        true
    ),
    (
        'Orange',
        NULL,
        'Fruits',
        47,
        0.9,
        11.8,
        0.1,
        2.4,
        9.4,
        0,
        131,
        '1 medium',
        'usda_fdc',
        true
    ),
    (
        'Strawberries',
        NULL,
        'Fruits',
        32,
        0.7,
        7.7,
        0.3,
        2.0,
        4.9,
        1,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Blueberries',
        NULL,
        'Fruits',
        57,
        0.7,
        14.5,
        0.3,
        2.4,
        10.0,
        1,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Raspberries',
        NULL,
        'Fruits',
        52,
        1.2,
        11.9,
        0.7,
        6.5,
        4.4,
        1,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Blackberries',
        NULL,
        'Fruits',
        43,
        1.4,
        9.6,
        0.5,
        5.3,
        4.9,
        1,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Grapes (Red/Green)',
        NULL,
        'Fruits',
        69,
        0.7,
        18.1,
        0.2,
        0.9,
        15.5,
        2,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Watermelon',
        NULL,
        'Fruits',
        30,
        0.6,
        7.6,
        0.2,
        0.4,
        6.2,
        1,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Cantaloupe',
        NULL,
        'Fruits',
        34,
        0.8,
        8.2,
        0.2,
        0.9,
        7.9,
        16,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Mango',
        NULL,
        'Fruits',
        60,
        0.8,
        15.0,
        0.4,
        1.6,
        13.7,
        1,
        165,
        '1 cup diced',
        'usda_fdc',
        true
    ),
    (
        'Pineapple',
        NULL,
        'Fruits',
        50,
        0.5,
        13.1,
        0.1,
        1.4,
        9.9,
        1,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Kiwi',
        NULL,
        'Fruits',
        61,
        1.1,
        14.7,
        0.5,
        3.0,
        9.0,
        3,
        69,
        '1 medium',
        'usda_fdc',
        true
    ),
    (
        'Peach',
        NULL,
        'Fruits',
        39,
        0.9,
        9.5,
        0.3,
        1.5,
        8.4,
        0,
        150,
        '1 medium',
        'usda_fdc',
        true
    ),
    (
        'Pear',
        NULL,
        'Fruits',
        57,
        0.4,
        15.2,
        0.1,
        3.1,
        9.7,
        1,
        178,
        '1 medium',
        'usda_fdc',
        true
    ),
    (
        'Plum',
        NULL,
        'Fruits',
        46,
        0.7,
        11.4,
        0.3,
        1.4,
        9.9,
        0,
        66,
        '1 medium',
        'usda_fdc',
        true
    ),
    (
        'Cherries',
        NULL,
        'Fruits',
        50,
        1.0,
        12.2,
        0.3,
        1.6,
        8.5,
        3,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Grapefruit',
        NULL,
        'Fruits',
        42,
        0.8,
        10.7,
        0.1,
        1.6,
        6.9,
        0,
        123,
        '1/2 fruit',
        'usda_fdc',
        true
    ),
    (
        'Avocado',
        NULL,
        'Fruits',
        160,
        2.0,
        8.5,
        14.7,
        6.7,
        0.7,
        7,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Dates (Medjool)',
        NULL,
        'Fruits',
        277,
        1.8,
        75.0,
        0.2,
        6.7,
        66.5,
        1,
        24,
        '1 date',
        'usda_fdc',
        true
    ),
    -- DAIRY (20 items) - Calcium & protein
    (
        'Milk (Whole)',
        NULL,
        'Dairy',
        61,
        3.2,
        4.8,
        3.3,
        0,
        5.1,
        43,
        244,
        '1 cup',
        'usda_fdc',
        true
    ),
    (
        'Milk (2%)',
        NULL,
        'Dairy',
        50,
        3.3,
        4.8,
        2.0,
        0,
        5.1,
        44,
        244,
        '1 cup',
        'usda_fdc',
        true
    ),
    (
        'Milk (1%)',
        NULL,
        'Dairy',
        42,
        3.4,
        5.0,
        1.0,
        0,
        5.1,
        44,
        244,
        '1 cup',
        'usda_fdc',
        true
    ),
    (
        'Milk (Skim)',
        NULL,
        'Dairy',
        34,
        3.4,
        5.0,
        0.2,
        0,
        5.1,
        42,
        244,
        '1 cup',
        'usda_fdc',
        true
    ),
    (
        'Almond Milk (Unsweetened)',
        NULL,
        'Dairy',
        15,
        0.4,
        0.6,
        1.1,
        0.2,
        0,
        63,
        240,
        '1 cup',
        'usda_fdc',
        true
    ),
    (
        'Oat Milk',
        NULL,
        'Dairy',
        47,
        1.0,
        7.6,
        1.5,
        0.8,
        4.5,
        101,
        240,
        '1 cup',
        'internal',
        true
    ),
    (
        'Cheddar Cheese',
        NULL,
        'Dairy',
        403,
        22.9,
        3.1,
        33.3,
        0,
        0.5,
        653,
        28,
        '1 oz',
        'usda_fdc',
        true
    ),
    (
        'Mozzarella Cheese (Part-Skim)',
        NULL,
        'Dairy',
        280,
        27.5,
        3.1,
        17.1,
        0,
        1.1,
        619,
        28,
        '1 oz',
        'usda_fdc',
        true
    ),
    (
        'Parmesan Cheese (Grated)',
        NULL,
        'Dairy',
        431,
        38.5,
        4.1,
        28.6,
        0,
        0.9,
        1529,
        5,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Feta Cheese',
        NULL,
        'Dairy',
        264,
        14.2,
        4.1,
        21.3,
        0,
        4.1,
        1116,
        28,
        '1 oz',
        'usda_fdc',
        true
    ),
    (
        'Cream Cheese',
        NULL,
        'Dairy',
        342,
        5.9,
        5.5,
        34.2,
        0,
        3.8,
        321,
        28,
        '1 oz',
        'usda_fdc',
        true
    ),
    (
        'Sour Cream (Full-Fat)',
        NULL,
        'Dairy',
        193,
        2.4,
        4.6,
        19.0,
        0,
        3.4,
        54,
        30,
        '2 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Sour Cream (Low-Fat)',
        NULL,
        'Dairy',
        135,
        3.5,
        7.0,
        10.0,
        0,
        6.5,
        71,
        30,
        '2 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Heavy Cream',
        NULL,
        'Dairy',
        340,
        2.1,
        2.8,
        36.1,
        0,
        2.8,
        38,
        15,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Half and Half',
        NULL,
        'Dairy',
        130,
        2.9,
        4.3,
        11.5,
        0,
        4.1,
        49,
        15,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Butter (Salted)',
        NULL,
        'Fats',
        717,
        0.9,
        0.1,
        81.1,
        0,
        0.1,
        643,
        14,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Butter (Unsalted)',
        NULL,
        'Fats',
        717,
        0.9,
        0.1,
        81.1,
        0,
        0.1,
        11,
        14,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'String Cheese (Mozzarella)',
        NULL,
        'Dairy',
        280,
        28.0,
        2.8,
        17.1,
        0,
        1.0,
        643,
        28,
        '1 stick',
        'usda_fdc',
        true
    ),
    (
        'Ricotta Cheese (Part-Skim)',
        NULL,
        'Dairy',
        138,
        11.4,
        5.1,
        7.9,
        0,
        0.3,
        125,
        100,
        '100g',
        'usda_fdc',
        true
    ),
    (
        'Brie Cheese',
        NULL,
        'Dairy',
        334,
        20.8,
        0.5,
        27.7,
        0,
        0.5,
        629,
        28,
        '1 oz',
        'usda_fdc',
        true
    ),
    -- FATS & OILS (15 items) - Essential fats
    (
        'Olive Oil (Extra Virgin)',
        NULL,
        'Fats',
        884,
        0,
        0,
        100.0,
        0,
        0,
        2,
        14,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Coconut Oil',
        NULL,
        'Fats',
        862,
        0,
        0,
        100.0,
        0,
        0,
        0,
        14,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Avocado Oil',
        NULL,
        'Fats',
        884,
        0,
        0,
        100.0,
        0,
        0,
        0,
        14,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Canola Oil',
        NULL,
        'Fats',
        884,
        0,
        0,
        100.0,
        0,
        0,
        0,
        14,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Almonds (Raw)',
        NULL,
        'Nuts',
        579,
        21.2,
        21.6,
        49.9,
        12.5,
        4.4,
        1,
        28,
        '1 oz',
        'usda_fdc',
        true
    ),
    (
        'Cashews (Raw)',
        NULL,
        'Nuts',
        553,
        18.2,
        30.2,
        43.9,
        3.3,
        5.9,
        12,
        28,
        '1 oz',
        'usda_fdc',
        true
    ),
    (
        'Walnuts (Raw)',
        NULL,
        'Nuts',
        654,
        15.2,
        13.7,
        65.2,
        6.7,
        2.6,
        2,
        28,
        '1 oz',
        'usda_fdc',
        true
    ),
    (
        'Pecans (Raw)',
        NULL,
        'Nuts',
        691,
        9.2,
        13.9,
        72.0,
        9.6,
        4.0,
        0,
        28,
        '1 oz',
        'usda_fdc',
        true
    ),
    (
        'Peanuts (Dry Roasted)',
        NULL,
        'Nuts',
        585,
        23.7,
        21.3,
        49.7,
        8.4,
        4.9,
        6,
        28,
        '1 oz',
        'usda_fdc',
        true
    ),
    (
        'Peanut Butter (Natural)',
        NULL,
        'Nuts',
        588,
        25.1,
        19.6,
        50.0,
        6.0,
        9.2,
        17,
        32,
        '2 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Almond Butter',
        NULL,
        'Nuts',
        614,
        20.3,
        18.8,
        55.5,
        10.3,
        4.4,
        1,
        32,
        '2 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Chia Seeds',
        NULL,
        'Nuts',
        486,
        16.5,
        42.1,
        30.7,
        34.4,
        0,
        16,
        12,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Flax Seeds (Ground)',
        NULL,
        'Nuts',
        534,
        18.3,
        28.9,
        42.2,
        27.3,
        1.6,
        30,
        12,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Sunflower Seeds',
        NULL,
        'Nuts',
        584,
        20.8,
        20.0,
        51.5,
        8.6,
        2.6,
        9,
        28,
        '1 oz',
        'usda_fdc',
        true
    ),
    (
        'Pumpkin Seeds',
        NULL,
        'Nuts',
        559,
        30.2,
        10.7,
        49.1,
        6.0,
        1.4,
        7,
        28,
        '1 oz',
        'usda_fdc',
        true
    ),
    -- BEVERAGES (15 items) - Hydration & supplements
    (
        'Black Coffee (Brewed)',
        NULL,
        'Beverages',
        1,
        0.1,
        0,
        0,
        0,
        0,
        2,
        240,
        '8 oz',
        'usda_fdc',
        true
    ),
    (
        'Coffee (With Cream, No Sugar)',
        NULL,
        'Beverages',
        20,
        0.4,
        0.7,
        1.7,
        0,
        0.7,
        9,
        240,
        '8 oz',
        'internal',
        true
    ),
    (
        'Green Tea (Brewed)',
        NULL,
        'Beverages',
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        240,
        '8 oz',
        'usda_fdc',
        true
    ),
    (
        'Black Tea (Brewed)',
        NULL,
        'Beverages',
        2,
        0,
        0.7,
        0,
        0,
        0,
        5,
        240,
        '8 oz',
        'usda_fdc',
        true
    ),
    (
        'Protein Shake (Whey + Water)',
        NULL,
        'Beverages',
        94,
        20.0,
        1.7,
        0.8,
        0,
        1.7,
        125,
        240,
        '8 oz',
        'internal',
        true
    ),
    (
        'Protein Shake (Whey + Milk)',
        NULL,
        'Beverages',
        149,
        23.2,
        6.5,
        4.1,
        0,
        6.6,
        167,
        240,
        '8 oz',
        'internal',
        true
    ),
    (
        'Orange Juice (100%)',
        NULL,
        'Beverages',
        45,
        0.7,
        10.4,
        0.2,
        0.2,
        8.4,
        1,
        240,
        '8 oz',
        'usda_fdc',
        true
    ),
    (
        'Apple Juice (100%)',
        NULL,
        'Beverages',
        46,
        0.1,
        11.3,
        0.1,
        0.2,
        9.6,
        4,
        240,
        '8 oz',
        'usda_fdc',
        true
    ),
    (
        'Coconut Water',
        NULL,
        'Beverages',
        19,
        0.7,
        3.7,
        0.2,
        1.1,
        2.6,
        105,
        240,
        '8 oz',
        'usda_fdc',
        true
    ),
    (
        'Sports Drink (Gatorade)',
        NULL,
        'Beverages',
        25,
        0,
        6.3,
        0,
        0,
        5.8,
        110,
        240,
        '8 oz',
        'internal',
        true
    ),
    (
        'Diet Soda',
        NULL,
        'Beverages',
        0,
        0,
        0.3,
        0,
        0,
        0,
        40,
        240,
        '8 oz',
        'usda_fdc',
        true
    ),
    (
        'Almond Milk Latte (Unsweetened)',
        NULL,
        'Beverages',
        13,
        0.8,
        1.0,
        0.8,
        0.2,
        0.5,
        63,
        240,
        '8 oz',
        'internal',
        true
    ),
    (
        'Pre-Workout (Generic)',
        NULL,
        'Beverages',
        20,
        0,
        5.0,
        0,
        0,
        0,
        200,
        240,
        '8 oz',
        'internal',
        true
    ),
    (
        'BCAA Drink',
        NULL,
        'Beverages',
        20,
        5.0,
        0,
        0,
        0,
        0,
        100,
        240,
        '8 oz',
        'internal',
        true
    ),
    (
        'Kombucha',
        NULL,
        'Beverages',
        12,
        0,
        3.0,
        0,
        0,
        2.0,
        10,
        240,
        '8 oz',
        'usda_fdc',
        true
    ),
    -- SNACKS & CONDIMENTS (20 items) - Flavor & convenience
    (
        'Honey',
        NULL,
        'Condiments',
        304,
        0.3,
        82.4,
        0,
        0.2,
        82.1,
        4,
        21,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Maple Syrup (Pure)',
        NULL,
        'Condiments',
        260,
        0,
        67.0,
        0.1,
        0,
        60.5,
        9,
        20,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Ketchup',
        NULL,
        'Condiments',
        101,
        1.0,
        25.8,
        0.1,
        0.3,
        21.3,
        907,
        17,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Mustard (Yellow)',
        NULL,
        'Condiments',
        66,
        4.0,
        5.8,
        3.6,
        3.3,
        2.0,
        1104,
        5,
        '1 tsp',
        'usda_fdc',
        true
    ),
    (
        'Mayonnaise (Full-Fat)',
        NULL,
        'Condiments',
        680,
        0.9,
        0.6,
        75.0,
        0,
        0.3,
        567,
        14,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Mayonnaise (Light)',
        NULL,
        'Condiments',
        333,
        0.4,
        10.0,
        31.7,
        0,
        6.7,
        600,
        14,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Ranch Dressing',
        NULL,
        'Condiments',
        458,
        1.4,
        5.6,
        47.2,
        0,
        3.3,
        1139,
        15,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Balsamic Vinegar',
        NULL,
        'Condiments',
        88,
        0.5,
        17.0,
        0,
        0,
        14.0,
        23,
        15,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Soy Sauce (Low Sodium)',
        NULL,
        'Condiments',
        53,
        8.1,
        4.9,
        0.1,
        0.8,
        1.7,
        3024,
        15,
        '1 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Sriracha Sauce',
        NULL,
        'Condiments',
        93,
        1.9,
        20.0,
        0.9,
        1.9,
        13.0,
        1067,
        5,
        '1 tsp',
        'usda_fdc',
        true
    ),
    (
        'Hummus',
        NULL,
        'Snacks',
        166,
        7.9,
        14.3,
        9.6,
        6.0,
        0.3,
        379,
        28,
        '2 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Guacamole',
        NULL,
        'Snacks',
        161,
        2.0,
        8.6,
        14.7,
        4.3,
        0.7,
        7,
        28,
        '2 tbsp',
        'internal',
        true
    ),
    (
        'Salsa (Chunky)',
        NULL,
        'Condiments',
        36,
        1.5,
        8.4,
        0.2,
        2.2,
        5.4,
        430,
        32,
        '2 tbsp',
        'usda_fdc',
        true
    ),
    (
        'Granola (Generic)',
        NULL,
        'Snacks',
        471,
        11.9,
        64.7,
        19.7,
        8.9,
        20.2,
        24,
        50,
        '1/2 cup',
        'usda_fdc',
        true
    ),
    (
        'Dark Chocolate (70-85% Cacao)',
        NULL,
        'Snacks',
        598,
        7.8,
        45.8,
        42.6,
        10.9,
        24.0,
        20,
        28,
        '1 oz',
        'usda_fdc',
        true
    ),
    (
        'Milk Chocolate',
        NULL,
        'Snacks',
        535,
        7.7,
        59.4,
        29.7,
        3.4,
        51.5,
        79,
        28,
        '1 oz',
        'usda_fdc',
        true
    ),
    (
        'Popcorn (Air-Popped)',
        NULL,
        'Snacks',
        387,
        12.9,
        77.8,
        4.5,
        14.5,
        0.9,
        8,
        30,
        '3 cups',
        'usda_fdc',
        true
    ),
    (
        'Tortilla Chips',
        NULL,
        'Snacks',
        503,
        7.0,
        61.1,
        24.9,
        5.3,
        1.1,
        322,
        28,
        '1 oz',
        'usda_fdc',
        true
    ),
    (
        'Rice Crackers',
        NULL,
        'Snacks',
        384,
        6.9,
        81.1,
        3.2,
        3.2,
        0,
        287,
        28,
        '1 oz',
        'usda_fdc',
        true
    ),
    (
        'Trail Mix (Nuts \u0026 Raisins)',
        NULL,
        'Snacks',
        462,
        13.8,
        44.9,
        29.1,
        5.5,
        31.8,
        46,
        40,
        '1/4 cup',
        'usda_fdc',
        true
    ) ON CONFLICT (name, brand) DO
UPDATE
SET category = EXCLUDED.category,
    calories_per_100g = EXCLUDED.calories_per_100g,
    protein_per_100g = EXCLUDED.protein_per_100g,
    carbs_per_100g = EXCLUDED.carbs_per_100g,
    fat_per_100g = EXCLUDED.fat_per_100g,
    fiber_per_100g = EXCLUDED.fiber_per_100g,
    sugar_per_100g = EXCLUDED.sugar_per_100g,
    sodium_per_100g = EXCLUDED.sodium_per_100g,
    serving_size_g = EXCLUDED.serving_size_g,
    serving_description = EXCLUDED.serving_description,
    source = EXCLUDED.source,
    is_verified = EXCLUDED.is_verified;
-- Verify count
DO $$
DECLARE food_count INTEGER;
BEGIN
SELECT COUNT(*) INTO food_count
FROM public.food_items
WHERE source IN ('usda_fdc', 'internal');
RAISE NOTICE 'Seeded % food items',
food_count;
IF food_count < 175 THEN RAISE WARNING 'Expected ~175 food items, but only % were inserted',
food_count;
END IF;
END $$;