// Canonical persona matrix for plan-engine snapshot testing.
//
// These personas are deterministic representatives of the combinatorial space
// our generator must handle. Every persona:
//   - matches the live `onboarding_answers.answers` shape (51 fields)
//   - normalizes into a valid UserState via buildUserState()
//   - has a unique seed when fed through buildUserStateSeed()
//
// DO NOT randomize. DO NOT fuzz. Add new personas explicitly when a real
// new corner is uncovered, then regenerate snapshots.

export type Persona = Record<string, unknown> & {
  readonly name: string;
  readonly tags: ReadonlyArray<string>;
};

// Default scaffolding all personas share. Individual personas override fields.
function base(): Record<string, unknown> {
  return {
    activity_level: "moderately_active",
    allergies_exclusions: ["none"],
    allergies_other_text: null,
    avg_steps: null,
    carb_tolerance: null,
    cooking_level: "basic",
    current_weight_lb: 180,
    dietary_preference: "anything",
    dietary_preference_other_text: null,
    dob: "1990-01-01",
    equipment_access: "full_gym",
    equipment_other_text: null,
    experience_level: "intermediate",
    first_meal_delay: "immediate",
    first_name: "Persona",
    goal_timeline: 16,
    goal_type: "maintain",
    height_ft: 5,
    height_in: 10,
    injuries: ["none"],
    injuries_other_text: null,
    last_meal_before_bed: "2hrs",
    last_name: "Test",
    meals_per_day: 4,
    minutes_per_workout: 60,
    preferred_carbs: ["rice", "oats", "sweet_potato"],
    preferred_days_off: ["sat", "sun"],
    preferred_fats: ["olive_oil", "almonds", "avocado"],
    preferred_proteins: ["chicken", "eggs", "greek_yogurt"],
    preferred_split_family: null,
    prep_auto_adjust_enabled: false,
    prep_discipline: null,
    prep_mode_enabled: false,
    prep_phase: null,
    progression_preference: "linear",
    refused_foods: [],
    refused_foods_other_text: null,
    session_emphasis: "general",
    sex: "male",
    sleep_hours: 7,
    step_tracking: false,
    target_date: null,
    target_weight_enabled: false,
    target_weight_lb: null,
    technique_preferences: [],
    traditional_meals: true,
    training_days: ["mon", "tue", "thu", "fri"],
    training_days_per_week: 4,
    training_time: "evening",
    userId: "persona-test",
    wake_time: "6_7am",
  };
}

function p(
  name: string,
  tags: ReadonlyArray<string>,
  overrides: Record<string, unknown>,
): Persona {
  return { name, tags, ...base(), ...overrides };
}

export const CANONICAL_PERSONAS: ReadonlyArray<Persona> = [
  // ---------- 1-5: Advanced males, varied goals ----------
  p(
    "p01_advanced_male_5day_fatloss_anything",
    ["advanced", "male", "5day", "fat_loss", "anything", "full_gym", "age_45_54", "split_ppl"],
    {
      dob: "1979-05-28",
      sex: "male",
      height_ft: 6,
      height_in: 3,
      current_weight_lb: 225,
      target_weight_lb: 200,
      target_weight_enabled: true,
      goal_type: "lose_weight",
      goal_timeline: 20,
      experience_level: "advanced",
      activity_level: "moderately_active",
      training_days: ["mon", "tue", "wed", "fri", "sat"],
      training_days_per_week: 5,
      preferred_days_off: ["thu", "sun"],
      minutes_per_workout: 75,
      training_time: "early_morning",
      preferred_split_family: "push_pull_legs",
      session_emphasis: "hypertrophy",
      progression_preference: "double_progression",
      preferred_proteins: ["chicken", "turkey", "beef"],
      preferred_carbs: ["rice", "oats", "sweet_potato"],
      preferred_fats: ["olive_oil", "almonds", "walnuts"],
      meals_per_day: 4,
      wake_time: "5_6am",
      carb_tolerance: "energized_satiated",
      cooking_level: "intermediate",
      sleep_hours: 7,
    },
  ),
  p(
    "p02_advanced_male_6day_gain_muscle_full_gym",
    ["advanced", "male", "6day", "gain_muscle", "anything", "full_gym", "age_25_34", "split_ppl"],
    {
      dob: "1996-03-15",
      sex: "male",
      height_ft: 5,
      height_in: 11,
      current_weight_lb: 195,
      target_weight_lb: 215,
      target_weight_enabled: true,
      goal_type: "gain_muscle",
      goal_timeline: 24,
      experience_level: "advanced",
      activity_level: "very_active",
      training_days: ["mon", "tue", "wed", "thu", "fri", "sat"],
      training_days_per_week: 6,
      preferred_days_off: ["sun"],
      minutes_per_workout: 90,
      training_time: "afternoon",
      preferred_split_family: "push_pull_legs",
      session_emphasis: "hypertrophy",
      progression_preference: "double_progression",
      meals_per_day: 5,
      preferred_proteins: ["chicken", "beef", "whey"],
      carb_tolerance: "high_carb_loving",
      cooking_level: "advanced",
      sleep_hours: 8,
    },
  ),
  p(
    "p03_advanced_male_4day_performance_upper_lower",
    ["advanced", "male", "4day", "performance", "anything", "full_gym", "age_35_44", "split_upper_lower"],
    {
      dob: "1986-07-20",
      sex: "male",
      height_ft: 6,
      height_in: 0,
      current_weight_lb: 200,
      goal_type: "performance",
      goal_timeline: 16,
      experience_level: "advanced",
      activity_level: "very_active",
      training_days: ["mon", "tue", "thu", "fri"],
      training_days_per_week: 4,
      preferred_days_off: ["wed", "sat", "sun"],
      minutes_per_workout: 75,
      training_time: "morning",
      preferred_split_family: "upper_lower",
      session_emphasis: "strength",
      progression_preference: "linear",
      meals_per_day: 4,
      cooking_level: "intermediate",
      sleep_hours: 7,
    },
  ),
  p(
    "p04_advanced_male_5day_recomp_home_gym",
    ["advanced", "male", "5day", "recomp", "anything", "home_gym", "age_35_44"],
    {
      dob: "1988-11-04",
      sex: "male",
      height_ft: 5,
      height_in: 10,
      current_weight_lb: 190,
      target_weight_lb: 185,
      target_weight_enabled: true,
      goal_type: "recomp",
      goal_timeline: 20,
      experience_level: "advanced",
      activity_level: "moderately_active",
      training_days: ["mon", "tue", "wed", "fri", "sat"],
      training_days_per_week: 5,
      preferred_days_off: ["thu", "sun"],
      minutes_per_workout: 60,
      training_time: "evening",
      equipment_access: "home_gym",
      meals_per_day: 4,
      preferred_proteins: ["chicken", "eggs", "cottage_cheese"],
      cooking_level: "intermediate",
      sleep_hours: 7,
    },
  ),
  p(
    "p05_advanced_male_3day_maintain_minimal",
    ["advanced", "male", "3day", "maintain", "anything", "minimal_equipment", "age_55_64"],
    {
      dob: "1965-09-12",
      sex: "male",
      height_ft: 5,
      height_in: 9,
      current_weight_lb: 175,
      goal_type: "maintain",
      goal_timeline: 12,
      experience_level: "advanced",
      activity_level: "lightly_active",
      training_days: ["mon", "wed", "fri"],
      training_days_per_week: 3,
      preferred_days_off: ["tue", "thu", "sat", "sun"],
      minutes_per_workout: 45,
      training_time: "morning",
      equipment_access: "minimal_equipment",
      meals_per_day: 3,
      cooking_level: "intermediate",
      sleep_hours: 7,
    },
  ),

  // ---------- 6-10: Intermediate, mixed sexes ----------
  p(
    "p06_intermediate_female_4day_fatloss_vegetarian",
    ["intermediate", "female", "4day", "fat_loss", "vegetarian", "full_gym", "age_25_34"],
    {
      dob: "1995-02-14",
      sex: "female",
      height_ft: 5,
      height_in: 5,
      current_weight_lb: 145,
      target_weight_lb: 130,
      target_weight_enabled: true,
      goal_type: "lose_weight",
      goal_timeline: 16,
      experience_level: "intermediate",
      activity_level: "moderately_active",
      training_days: ["mon", "tue", "thu", "fri"],
      training_days_per_week: 4,
      preferred_days_off: ["wed", "sat", "sun"],
      minutes_per_workout: 60,
      training_time: "evening",
      dietary_preference: "vegetarian",
      meals_per_day: 4,
      preferred_proteins: ["greek_yogurt", "eggs", "cottage_cheese", "tofu"],
      preferred_carbs: ["oats", "quinoa", "sweet_potato"],
      preferred_fats: ["almonds", "avocado", "olive_oil"],
      carb_tolerance: "carb_sensitive",
      cooking_level: "intermediate",
      sleep_hours: 7,
      step_tracking: true,
      avg_steps: 8500,
    },
  ),
  p(
    "p07_intermediate_female_5day_gain_muscle_anything",
    ["intermediate", "female", "5day", "gain_muscle", "anything", "full_gym", "age_25_34"],
    {
      dob: "1996-08-22",
      sex: "female",
      height_ft: 5,
      height_in: 7,
      current_weight_lb: 140,
      target_weight_lb: 150,
      target_weight_enabled: true,
      goal_type: "gain_muscle",
      goal_timeline: 24,
      experience_level: "intermediate",
      activity_level: "very_active",
      training_days: ["mon", "tue", "wed", "fri", "sat"],
      training_days_per_week: 5,
      preferred_days_off: ["thu", "sun"],
      minutes_per_workout: 75,
      training_time: "evening",
      preferred_split_family: "upper_lower",
      session_emphasis: "hypertrophy",
      meals_per_day: 5,
      cooking_level: "advanced",
      sleep_hours: 8,
    },
  ),
  p(
    "p08_intermediate_male_4day_recomp_pescatarian",
    ["intermediate", "male", "4day", "recomp", "pescatarian", "full_gym", "age_35_44"],
    {
      dob: "1985-04-18",
      sex: "male",
      height_ft: 5,
      height_in: 11,
      current_weight_lb: 185,
      target_weight_lb: 180,
      target_weight_enabled: true,
      goal_type: "recomp",
      goal_timeline: 20,
      experience_level: "intermediate",
      activity_level: "moderately_active",
      training_days: ["mon", "tue", "thu", "fri"],
      training_days_per_week: 4,
      preferred_days_off: ["wed", "sat", "sun"],
      minutes_per_workout: 60,
      training_time: "midday",
      dietary_preference: "pescatarian",
      preferred_proteins: ["salmon", "tuna", "shrimp", "eggs"],
      meals_per_day: 4,
      cooking_level: "intermediate",
      sleep_hours: 7,
    },
  ),
  p(
    "p09_intermediate_female_3day_maintain_keto",
    ["intermediate", "female", "3day", "maintain", "keto", "home_gym", "age_35_44"],
    {
      dob: "1987-10-30",
      sex: "female",
      height_ft: 5,
      height_in: 4,
      current_weight_lb: 138,
      goal_type: "maintain",
      goal_timeline: 12,
      experience_level: "intermediate",
      activity_level: "lightly_active",
      training_days: ["mon", "wed", "fri"],
      training_days_per_week: 3,
      preferred_days_off: ["tue", "thu", "sat", "sun"],
      minutes_per_workout: 45,
      training_time: "morning",
      equipment_access: "home_gym",
      dietary_preference: "keto",
      preferred_proteins: ["beef", "eggs", "chicken_thighs"],
      preferred_carbs: ["leafy_greens", "broccoli", "cauliflower"],
      preferred_fats: ["avocado", "olive_oil", "butter"],
      carb_tolerance: "carb_sensitive",
      meals_per_day: 3,
      cooking_level: "advanced",
      sleep_hours: 7,
    },
  ),
  p(
    "p10_intermediate_male_5day_performance_anything",
    ["intermediate", "male", "5day", "performance", "anything", "full_gym", "age_25_34"],
    {
      dob: "1994-06-10",
      sex: "male",
      height_ft: 5,
      height_in: 10,
      current_weight_lb: 175,
      goal_type: "performance",
      goal_timeline: 16,
      experience_level: "intermediate",
      activity_level: "very_active",
      training_days: ["mon", "tue", "wed", "fri", "sat"],
      training_days_per_week: 5,
      preferred_days_off: ["thu", "sun"],
      minutes_per_workout: 75,
      training_time: "afternoon",
      session_emphasis: "athletic",
      preferred_split_family: "upper_lower",
      progression_preference: "linear",
      meals_per_day: 4,
      cooking_level: "intermediate",
      sleep_hours: 8,
    },
  ),

  // ---------- 11-15: Beginners, varied ----------
  p(
    "p11_beginner_male_3day_fatloss_full_gym",
    ["beginner", "male", "3day", "fat_loss", "anything", "full_gym", "age_25_34"],
    {
      dob: "1995-12-01",
      sex: "male",
      height_ft: 5,
      height_in: 10,
      current_weight_lb: 215,
      target_weight_lb: 185,
      target_weight_enabled: true,
      goal_type: "lose_weight",
      goal_timeline: 24,
      experience_level: "beginner",
      activity_level: "sedentary",
      training_days: ["mon", "wed", "fri"],
      training_days_per_week: 3,
      preferred_days_off: ["tue", "thu", "sat", "sun"],
      minutes_per_workout: 45,
      training_time: "evening",
      meals_per_day: 3,
      cooking_level: "basic",
      sleep_hours: 6,
    },
  ),
  p(
    "p12_beginner_female_2day_fatloss_bodyweight",
    ["beginner", "female", "2day", "fat_loss", "anything", "bodyweight_only", "age_45_54"],
    {
      dob: "1975-03-22",
      sex: "female",
      height_ft: 5,
      height_in: 4,
      current_weight_lb: 175,
      target_weight_lb: 145,
      target_weight_enabled: true,
      goal_type: "lose_weight",
      goal_timeline: 32,
      experience_level: "beginner",
      activity_level: "lightly_active",
      training_days: ["tue", "sat"],
      training_days_per_week: 2,
      preferred_days_off: ["mon", "wed", "thu", "fri", "sun"],
      minutes_per_workout: 30,
      training_time: "morning",
      equipment_access: "bodyweight_only",
      meals_per_day: 3,
      cooking_level: "basic",
      sleep_hours: 6,
    },
  ),
  p(
    "p13_beginner_male_3day_gain_muscle_minimal",
    ["beginner", "male", "3day", "gain_muscle", "anything", "minimal_equipment", "age_25_34"],
    {
      dob: "1998-01-15",
      sex: "male",
      height_ft: 5,
      height_in: 9,
      current_weight_lb: 140,
      target_weight_lb: 165,
      target_weight_enabled: true,
      goal_type: "gain_muscle",
      goal_timeline: 32,
      experience_level: "beginner",
      activity_level: "lightly_active",
      training_days: ["mon", "wed", "fri"],
      training_days_per_week: 3,
      preferred_days_off: ["tue", "thu", "sat", "sun"],
      minutes_per_workout: 60,
      training_time: "evening",
      equipment_access: "minimal_equipment",
      meals_per_day: 4,
      cooking_level: "basic",
      sleep_hours: 8,
    },
  ),
  p(
    "p14_beginner_female_4day_recomp_vegan",
    ["beginner", "female", "4day", "recomp", "vegan", "full_gym", "age_25_34"],
    {
      dob: "1997-11-09",
      sex: "female",
      height_ft: 5,
      height_in: 6,
      current_weight_lb: 155,
      target_weight_lb: 150,
      target_weight_enabled: true,
      goal_type: "recomp",
      goal_timeline: 20,
      experience_level: "beginner",
      activity_level: "moderately_active",
      training_days: ["mon", "tue", "thu", "fri"],
      training_days_per_week: 4,
      preferred_days_off: ["wed", "sat", "sun"],
      minutes_per_workout: 45,
      training_time: "evening",
      dietary_preference: "vegan",
      preferred_proteins: ["tofu", "tempeh", "lentils", "seitan"],
      preferred_carbs: ["oats", "quinoa", "brown_rice"],
      preferred_fats: ["almonds", "walnuts", "avocado"],
      meals_per_day: 4,
      cooking_level: "intermediate",
      sleep_hours: 7,
    },
  ),
  p(
    "p15_beginner_male_3day_maintain_home_gym",
    ["beginner", "male", "3day", "maintain", "anything", "home_gym", "age_35_44"],
    {
      dob: "1986-02-05",
      sex: "male",
      height_ft: 5,
      height_in: 11,
      current_weight_lb: 180,
      goal_type: "maintain",
      goal_timeline: 12,
      experience_level: "beginner",
      activity_level: "moderately_active",
      training_days: ["mon", "wed", "fri"],
      training_days_per_week: 3,
      preferred_days_off: ["tue", "thu", "sat", "sun"],
      minutes_per_workout: 45,
      training_time: "morning",
      equipment_access: "home_gym",
      meals_per_day: 3,
      cooking_level: "basic",
      sleep_hours: 7,
    },
  ),

  // ---------- 16-20: Injuries ----------
  p(
    "p16_intermediate_male_4day_recomp_back_injury",
    ["intermediate", "male", "4day", "recomp", "anything", "full_gym", "injury_back", "age_35_44"],
    {
      dob: "1984-06-25",
      sex: "male",
      height_ft: 6,
      height_in: 0,
      current_weight_lb: 200,
      target_weight_lb: 190,
      target_weight_enabled: true,
      goal_type: "recomp",
      goal_timeline: 24,
      experience_level: "intermediate",
      activity_level: "moderately_active",
      training_days: ["mon", "tue", "thu", "fri"],
      training_days_per_week: 4,
      preferred_days_off: ["wed", "sat", "sun"],
      minutes_per_workout: 60,
      training_time: "evening",
      injuries: ["lower_back"],
      injuries_other_text: "L4/L5 disc",
      meals_per_day: 4,
      cooking_level: "intermediate",
      sleep_hours: 7,
    },
  ),
  p(
    "p17_intermediate_female_4day_fatloss_knee_injury",
    ["intermediate", "female", "4day", "fat_loss", "anything", "full_gym", "injury_knee", "age_35_44"],
    {
      dob: "1985-08-12",
      sex: "female",
      height_ft: 5,
      height_in: 5,
      current_weight_lb: 165,
      target_weight_lb: 140,
      target_weight_enabled: true,
      goal_type: "lose_weight",
      goal_timeline: 24,
      experience_level: "intermediate",
      activity_level: "moderately_active",
      training_days: ["mon", "tue", "thu", "fri"],
      training_days_per_week: 4,
      preferred_days_off: ["wed", "sat", "sun"],
      minutes_per_workout: 60,
      training_time: "morning",
      injuries: ["knee"],
      injuries_other_text: "right meniscus",
      meals_per_day: 4,
      cooking_level: "basic",
      sleep_hours: 7,
    },
  ),
  p(
    "p18_advanced_male_5day_performance_shoulder_injury",
    ["advanced", "male", "5day", "performance", "anything", "full_gym", "injury_shoulder", "age_25_34"],
    {
      dob: "1993-09-30",
      sex: "male",
      height_ft: 5,
      height_in: 11,
      current_weight_lb: 195,
      goal_type: "performance",
      goal_timeline: 16,
      experience_level: "advanced",
      activity_level: "very_active",
      training_days: ["mon", "tue", "wed", "fri", "sat"],
      training_days_per_week: 5,
      preferred_days_off: ["thu", "sun"],
      minutes_per_workout: 75,
      training_time: "afternoon",
      injuries: ["shoulder"],
      injuries_other_text: "left labrum",
      session_emphasis: "strength",
      preferred_split_family: "upper_lower",
      meals_per_day: 5,
      cooking_level: "intermediate",
      sleep_hours: 8,
    },
  ),

  // ---------- 19-21: Refused foods / allergies ----------
  p(
    "p19_intermediate_female_4day_fatloss_dairy_allergy",
    ["intermediate", "female", "4day", "fat_loss", "anything", "full_gym", "allergy", "age_25_34"],
    {
      dob: "1996-04-18",
      sex: "female",
      height_ft: 5,
      height_in: 5,
      current_weight_lb: 150,
      target_weight_lb: 135,
      target_weight_enabled: true,
      goal_type: "lose_weight",
      goal_timeline: 16,
      experience_level: "intermediate",
      activity_level: "moderately_active",
      training_days: ["mon", "tue", "thu", "fri"],
      training_days_per_week: 4,
      preferred_days_off: ["wed", "sat", "sun"],
      minutes_per_workout: 60,
      training_time: "evening",
      allergies_exclusions: ["dairy", "shellfish"],
      allergies_other_text: "lactose intolerant",
      refused_foods: ["liver", "tuna"],
      meals_per_day: 4,
      cooking_level: "intermediate",
      sleep_hours: 7,
    },
  ),
  p(
    "p20_intermediate_male_5day_gain_muscle_refused_foods",
    ["intermediate", "male", "5day", "gain_muscle", "anything", "full_gym", "refused_foods", "age_25_34"],
    {
      dob: "1995-07-07",
      sex: "male",
      height_ft: 6,
      height_in: 1,
      current_weight_lb: 185,
      target_weight_lb: 205,
      target_weight_enabled: true,
      goal_type: "gain_muscle",
      goal_timeline: 24,
      experience_level: "intermediate",
      activity_level: "very_active",
      training_days: ["mon", "tue", "wed", "fri", "sat"],
      training_days_per_week: 5,
      preferred_days_off: ["thu", "sun"],
      minutes_per_workout: 75,
      training_time: "evening",
      refused_foods: ["tofu", "tempeh", "mushrooms", "cottage_cheese"],
      refused_foods_other_text: "no organ meats",
      meals_per_day: 5,
      preferred_split_family: "push_pull_legs",
      cooking_level: "intermediate",
      sleep_hours: 8,
    },
  ),
  p(
    "p21_beginner_male_3day_fatloss_nut_allergy",
    ["beginner", "male", "3day", "fat_loss", "anything", "home_gym", "allergy", "refused_foods", "age_35_44"],
    {
      dob: "1985-03-03",
      sex: "male",
      height_ft: 5,
      height_in: 8,
      current_weight_lb: 220,
      target_weight_lb: 190,
      target_weight_enabled: true,
      goal_type: "lose_weight",
      goal_timeline: 28,
      experience_level: "beginner",
      activity_level: "sedentary",
      training_days: ["mon", "wed", "fri"],
      training_days_per_week: 3,
      preferred_days_off: ["tue", "thu", "sat", "sun"],
      minutes_per_workout: 45,
      training_time: "evening",
      equipment_access: "home_gym",
      allergies_exclusions: ["tree_nuts", "peanuts"],
      allergies_other_text: "severe peanut allergy",
      refused_foods: ["cilantro", "olives"],
      meals_per_day: 3,
      preferred_fats: ["olive_oil", "avocado", "seeds"],
      cooking_level: "basic",
      sleep_hours: 6,
    },
  ),

  // ---------- 22-23: Elderly + sedentary edge cases ----------
  p(
    "p22_beginner_female_2day_maintain_elderly_sedentary",
    ["beginner", "female", "2day", "maintain", "anything", "bodyweight_only", "elderly", "sedentary", "age_65_plus"],
    {
      dob: "1955-04-12",
      sex: "female",
      height_ft: 5,
      height_in: 3,
      current_weight_lb: 145,
      goal_type: "maintain",
      goal_timeline: 12,
      experience_level: "beginner",
      activity_level: "sedentary",
      training_days: ["tue", "thu"],
      training_days_per_week: 2,
      preferred_days_off: ["mon", "wed", "fri", "sat", "sun"],
      minutes_per_workout: 30,
      training_time: "morning",
      equipment_access: "bodyweight_only",
      injuries: ["knee", "shoulder"],
      injuries_other_text: "arthritis both knees",
      meals_per_day: 3,
      cooking_level: "basic",
      wake_time: "6_7am",
      last_meal_before_bed: "3hrs",
      sleep_hours: 7,
    },
  ),
  p(
    "p23_beginner_male_3day_fatloss_elderly_sedentary",
    ["beginner", "male", "3day", "fat_loss", "anything", "minimal_equipment", "elderly", "sedentary", "age_65_plus"],
    {
      dob: "1952-10-08",
      sex: "male",
      height_ft: 5,
      height_in: 8,
      current_weight_lb: 210,
      target_weight_lb: 185,
      target_weight_enabled: true,
      goal_type: "lose_weight",
      goal_timeline: 32,
      experience_level: "beginner",
      activity_level: "sedentary",
      training_days: ["mon", "wed", "fri"],
      training_days_per_week: 3,
      preferred_days_off: ["tue", "thu", "sat", "sun"],
      minutes_per_workout: 30,
      training_time: "morning",
      equipment_access: "minimal_equipment",
      injuries: ["lower_back"],
      injuries_other_text: "chronic lower back stiffness",
      meals_per_day: 3,
      cooking_level: "basic",
      wake_time: "6_7am",
      sleep_hours: 7,
    },
  ),

  // ---------- 24-26: Additional coverage (extra activity, age <25, meals=6) ----------
  p(
    "p24_intermediate_female_5day_performance_extra_active",
    ["intermediate", "female", "5day", "performance", "anything", "full_gym", "age_under_25", "extra_active"],
    {
      dob: "2003-05-19",
      sex: "female",
      height_ft: 5,
      height_in: 8,
      current_weight_lb: 148,
      goal_type: "performance",
      goal_timeline: 16,
      experience_level: "intermediate",
      activity_level: "extra_active",
      training_days: ["mon", "tue", "wed", "fri", "sat"],
      training_days_per_week: 5,
      preferred_days_off: ["thu", "sun"],
      minutes_per_workout: 90,
      training_time: "morning",
      session_emphasis: "athletic",
      meals_per_day: 5,
      step_tracking: true,
      avg_steps: 14000,
      cooking_level: "intermediate",
      sleep_hours: 8,
    },
  ),
  p(
    "p25_advanced_male_5day_gain_muscle_5meals_mediterranean",
    ["advanced", "male", "5day", "gain_muscle", "mediterranean", "full_gym", "age_45_54", "split_upper_lower"],
    {
      dob: "1978-12-22",
      sex: "male",
      height_ft: 5,
      height_in: 11,
      current_weight_lb: 190,
      target_weight_lb: 205,
      target_weight_enabled: true,
      goal_type: "gain_muscle",
      goal_timeline: 24,
      experience_level: "advanced",
      activity_level: "very_active",
      training_days: ["mon", "tue", "wed", "fri", "sat"],
      training_days_per_week: 5,
      preferred_days_off: ["thu", "sun"],
      minutes_per_workout: 75,
      training_time: "evening",
      preferred_split_family: "upper_lower",
      dietary_preference: "mediterranean",
      meals_per_day: 5,
      preferred_proteins: ["salmon", "chicken", "greek_yogurt"],
      preferred_fats: ["olive_oil", "almonds", "walnuts"],
      cooking_level: "advanced",
      sleep_hours: 7,
    },
  ),
  p(
    "p26_intermediate_male_4day_maintain_55_64",
    ["intermediate", "male", "4day", "maintain", "anything", "full_gym", "age_55_64"],
    {
      dob: "1968-01-29",
      sex: "male",
      height_ft: 5,
      height_in: 10,
      current_weight_lb: 185,
      goal_type: "maintain",
      goal_timeline: 12,
      experience_level: "intermediate",
      activity_level: "moderately_active",
      training_days: ["mon", "tue", "thu", "fri"],
      training_days_per_week: 4,
      preferred_days_off: ["wed", "sat", "sun"],
      minutes_per_workout: 60,
      training_time: "morning",
      meals_per_day: 4,
      cooking_level: "intermediate",
      sleep_hours: 7,
    },
  ),
] as const;
